SwissDataScienceCenter/renku-python

README.rst, renga/client/projects.py
closes #29 
a204096 closes #23
=> Remove trailing slash from projects url

renga/api/client.py, renga/cli/_config.py, renga/cli/notebooks.py, renga/client.py, renga/models/deployer.py, renga/models/storage.py
+ bugfix for `FileHandle` client and project config parsing
=> Reuse notebook context

renga/cli/notebooks.py, tests/test_cli.py
allows the following:
```
$ renga notebooks launch --image jupyter/datascience-notebook
```
The context is reused if the same image is requested multiple times in a project.
closes #41
=> notebooks: allow user to specify image

renga/api/explorer.py, renga/models/_datastructures.py, renga/models/storage.py, tests/conftest.py, tests/test_client.py
use the explorer API to retrieve a file
relates to #52 because it makes it possible to get the file name via the API
=> api: use explorer to retrieve file

.dockerignore, .travis.yml, .travis/deploy-docker.sh, Dockerfile, renga/cli/_options.py, renga/cli/add.py, renga/cli/notebooks.py, renga/models/deployer.py, renga/notebook.py, setup.py, tests/test_cli.py, tests/test_notebook.py
=> notebooks: run from an existing file

renga/cli/_options.py, renga/cli/init.py, tests/test_cli.py
=> cli: store project endpoint from argument

.travis.yml, .travis/deploy-docker.sh
=> docker: publish rengahub/minimal-notebook

Dockerfile, renga/cli/deployments.py, renga/cli/notebooks.py, renga/client.py, renga/models/deployer.py, renga/notebook.py, tests/conftest.py, tests/test_cli.py, tests/test_client.py, tests/test_notebook.py
=> client: get current_context and its inputs

renga/cli/_config.py, renga/cli/_group.py, renga/cli/add.py, renga/cli/init.py, renga/cli/io.py, tests/test_cli.py
Addresses issues #62 and #64. Please see them for more details.
=> cli: improvements of I/O

.dockerignore, .travis.yml, .travis/deploy-docker.sh, Dockerfile.template, MANIFEST.in, Makefile
=> docker: build and push all notebook image variants

Makefile
=> docker: fix wrong dependency in Makefile

renga/cli/_group.py, tests/test_cli.py
=> cli: fix error on buckets without command

renga/api/deployer.py, renga/cli/deployments.py, renga/models/deployer.py, tests/conftest.py, tests/test_cli.py
* add state and creation time to executions listing
* add creation time to contexts listing
* add logs command to executions
also: 
* remove `context-id` from executions listing (redundant)
* add url to executions column
closes #86
=> add missing cli functionality

renga/cli/_config.py
=> allow for empty config path

renga/cli/_ascii.py, renga/cli/log.py
=> cli: refactored graph display for log command

renga/cli/_repo.py, renga/cli/datasets.py, renga/models/_jsonld.py, renga/models/dataset.py, renga/models/projects.py, tests/conftest.py, tests/test_cli.py, tests/test_dataset.py
=> models: add JSON-LD context for datasets

renga/cli/_graph.py, renga/cli/workflow.py, renga/models/cwl/_ascwl.py, tests/test_cli.py
=> cli: create workflow for given outputs

renga/cli/_repo.py, renga/cli/datasets.py, renga/models/_jsonld.py, renga/models/dataset.py, renga/models/projects.py
=> dataset: fix paths and context nesting

renga/cli/_ascii.py, renga/cli/_graph.py, renga/cli/_repo.py, renga/cli/datasets.py, renga/cli/status.py, renga/models/_jsonld.py, renga/models/dataset.py, renga/models/projects.py, tests/test_cli.py
=> cli: fix status for symlinked files

renga/cli/notebooks.py, renga/cli/runner.py, setup.py
=> setup: fix installation without extras

renga/cli/.gitlab-ci.yml, renga/cli/runner.py
=> cli: keep GitLab checked out code up-to-date

docs/models.rst, renga/models/_jsonld.py, renga/models/datasets.py
addresses https://github.com/SwissDataScienceCenter/renga/issues/135
=> docs: include context and type in models

renga/cli/_ascii.py, renga/cli/_graph.py, renga/cli/update.py
Solves problem with files generated by a workflow.
=> cli: fix detection of dirty files

MANIFEST.in, renga/api/repository.py, renga/data/__init__.py, renga/data/gitignore.default
=> add a more complete gitignore

renga/cli/_git.py, renga/errors.py, setup.py
Can we rely on an output of `git status`?
```console
$ touch x
$ renga run touch y
Error: The repository is dirty. Please use the "git" command to clean it.
On branch master
Untracked files:
(use "git add <file>..." to include in what will be committed)
x
nothing added to commit but untracked files present (use "git add" to track)
Once you have added the untracked files, commit them with "git commit".
```
---
addresses https://github.com/SwissDataScienceCenter/renga/issues/186
=> Show git status

renku/api/client.py, renku/cli/_ascii.py, renku/cli/_git.py, renku/cli/_graph.py, renku/cli/log.py, renku/cli/run.py, renku/cli/status.py, renku/cli/update.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/types.py, tests/conftest.py, tests/test_cwl.py
Fixes generated CWL files when running `renku run` from a sub-directory.
=> cli: support running 'renku run' from subdir

renku/cli/update.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/parameter.py, setup.py, tests/test_cli.py, tests/test_cwl.py
=> cli: fix update on files in subdirectories

renku/cli/_git.py, tests/test_cli.py
=> cli: clean std streams on error

renku/cli/status.py, renku/cli/update.py
=> cli: show update hint and progress

renku/errors.py, renku/models/cwl/command_line_tool.py, tests/test_cli.py
=> cli: better output related errors

renku/cli/_echo.py, renku/cli/dataset.py, renku/cli/update.py, tests/test_cli.py
=> cli: add multiple files to a dataset at once

renku/api/datasets.py, renku/cli/dataset.py, tests/test_cli.py
=> cli: new --relative-to option for dataset addition

docs/cli.rst, renku/cli/_graph.py, renku/cli/log.py, renku/cli/run.py, renku/cli/status.py, renku/cli/update.py, tests/test_cli.py
=> docs: info about cli log, run, status and update

renku/api/datasets.py, renku/version.py, tests/test_cli.py
=> cli: support --relative-to for datasets in git

renku/cli/_graph.py, renku/cli/update.py, renku/models/cwl/command_line_tool.py, tests/test_cli.py
=> cli: update siblings and unmodifed files

MANIFEST.in, renku/cli/.gitlab-ci.yml, renku/cli/Dockerfile, renku/cli/runner.py
has been tested against https://github.com/SwissDataScienceCenter/renku/pull/260
closes #207
=> cli: update init for image builds

renku/api/datasets.py, renku/api/repository.py, renku/cli/_cwl.py, renku/cli/_git.py, renku/cli/_graph.py, renku/cli/_options.py, renku/cli/init.py, renku/cli/update.py, renku/models/cwl/command_line_tool.py
=> cli: mkdir, commit message, clean-up

docs/cli.rst, renku/cli/init.py, renku/cli/rerun.py, renku/cli/update.py, setup.py, tests/test_cli.py
- fixes missing articles
- fixes path normalization in update command
---
NOTE: there is a code duplication between `update` and `rerun` commands that will be refactored later.
=>  cli: simple rerun command

.travis.yml, MANIFEST.in, renku/api/datasets.py, renku/api/repository.py, renku/cli/_cwl.py, renku/cli/_graph.py, renku/cli/runner.py, renku/errors.py, renku/models/cwl/_ascwl.py, setup.py, snap/snapcraft.yaml, tests/test_cli.py
```console
$ docker run -v $(pwd):$(pwd) -t snapcore/snapcraft:stable sh -c "apt update -qq && cd $(pwd) && snapcraft"
```
=> snap: initial configuration

renku/models/_datastructures.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/process_requirements.py, renku/models/cwl/types.py, tests/test_cli.py
=> cwl: support for initial work dir requirement

renku/api/repository.py, renku/errors.py, renku/models/datasets.py
=> api: check git name and email is configuration

renku/cli/.gitlab-ci.yml, renku/models/cwl/command_line_tool.py, tests/test_cwl.py
=> cwl: simple tool str formatting

renku/cli/rerun.py, setup.py, tests/test_cli.py
=> cli: support rerun with editable inputs

README.rst
=> docs: alternative installations

renku/cli/_options.py, renku/cli/rerun.py, renku/cli/update.py
=> docs: document --with-siblings option

renku/cli/_ascii.py, renku/cli/_graph.py
=> graph: resolve paths in submodules

renku/cli/.gitlab-ci.yml, renku/cli/log.py, renku/models/cwl/command_line_tool.py, setup.py, tests/test_cli.py
=> cli: output formats for log

renku/cli/rerun.py
@ciyer it fixes the problem with your "toy" project.
---
(closes #242)
=> cli: move all outputs after rerun

Dockerfile.gitlab-runner, Dockerfile.notebook.template, Dockerfile.renku-python
=> docker: install git-lfs

renku/cli/_graph.py, renku/cli/status.py, renku/models/cwl/command_line_tool.py, tests/test_cli.py
=> cli: improve handling of deleted files

renku/cli/.gitlab-ci.yml
=> cli: add git related variables in .gitlab-ci.yml

.gitignore, .travis.yml, MANIFEST.in, Makefile, Pipfile, Pipfile.lock, conftest.py, renku/cli/_cwl.py, renku/cli/_git.py, renku/cli/_graph.py, renku/cli/run.py, renku/data/pre-commit.sh, renku/errors.py, renku/models/cwl/command_line_tool.py, setup.py, tests/test_cli.py
=> Python 3.7 and new CWLTool

renku/errors.py
=> errors: better message for unmodified outputs

renku/api/client.py, renku/api/repository.py, renku/cli/_graph.py, renku/cli/log.py, renku/cli/run.py, renku/models/_datastructures.py, renku/models/cwl/_ascwl.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/parameter.py, renku/models/cwl/process.py, renku/models/cwl/process_requirements.py, renku/models/cwl/types.py, tests/test_cli.py, tests/test_cwl.py
Simple input/output directory detection.
=> cwl: detect output directories

renku/cli/_graph.py, setup.py, tests/test_cli.py
=> cli: detect changes in input directories

renku/cli/_git.py
Covers corner cases detected in #280 and makes the code more robust.
(closes #280)
=> cli: fix std stream detection on index diff

renku/cli/_git.py, renku/cli/init.py, tests/test_cli.py
Create a project directory if it does not exists to mimic behavior of `git init foo`.
Fixes #272
=> cli: renku init creates directory

renku/api/datasets.py, renku/api/repository.py, renku/cli/__init__.py, renku/cli/_ascii.py, renku/cli/_git.py, renku/cli/_graph.py, setup.py
=> global: removal of pkg_resources

conftest.py, renku/api/repository.py, renku/cli/_ascii.py, renku/cli/_docker.py, renku/cli/_graph.py, renku/cli/log.py, renku/cli/rerun.py, renku/cli/runner.py, renku/cli/show.py, renku/cli/update.py, renku/cli/workflow.py, renku/models/commit.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/process.py, renku/models/cwl/workflow.py
This is an initial refactoring of recursive graph exploration to an iterative one.
addresses #287
=> graph: refactored commit parsing

docs/provenance.rst, renku/api/repository.py, renku/cli/_format.py, renku/cli/log.py, renku/models/provenance.py, tests/test_cli.py
Cleans up the log output formats and few missing nodes and edges.
Addresses #306
=> cli: output formats and metadata

renku/api/repository.py, renku/cli/_ascii.py, renku/cli/_graph.py, renku/cli/status.py, renku/cli/update.py, renku/cli/workflow.py, renku/models/cwl/__init__.py, renku/models/provenance.py, tests/test_cli.py
Simplifies status detection and adds test for usage of modified tool.
Fixes #295 
=> cwl: support tool edits

renku/cli/_git.py, renku/models/provenance.py
- Adds commit parents and sw agent to RDF representation.
- Tracks starting time of a renku command in the commit authored date.
fixes #306 
fixes #296
=> cwl: add commit parents and sw agent

docs/provenance.rst, renku/cli/_git.py, renku/models/projects.py, renku/models/provenance.py, renku/models/provenance/__init__.py, renku/models/provenance/activities.py, renku/models/provenance/agents.py, renku/models/provenance/entities.py, renku/models/provenance/expanded.py, renku/models/provenance/qualified.py
Simply refactores `renku.models.provenance` into a module.
=> models: provenance split

docs/provenance.rst, renku/cli/_git.py, renku/models/cwl/command_line_tool.py, renku/models/projects.py, renku/models/provenance.py, renku/models/provenance/__init__.py, renku/models/provenance/activities.py, renku/models/provenance/agents.py, renku/models/provenance/entities.py, renku/models/provenance/expanded.py, renku/models/provenance/qualified.py, tests/test_cli.py
Include timezone information in exported data.
closes #317 
=> models: export datetime with tzinfo

Pipfile.lock, renku/cli/_ascii.py, renku/cli/_cwl.py, renku/cli/_graph.py, renku/cli/rerun.py, renku/cli/show.py, renku/cli/workflow.py, renku/models/cwl/__init__.py, renku/models/cwl/_ascwl.py, renku/models/cwl/parameter.py, renku/models/cwl/workflow.py, renku/models/provenance/activities.py, renku/models/provenance/entities.py, tests/test_cli.py, tests/test_cwl.py
Links files to output directory.
closes #300
---
NOTE: it still misses a selection step if you would like to rerun the whole workflow.
=> models: link files to output directory

docs/provenance.rst, renku/cli/show.py, renku/models/provenance/__init__.py, tests/test_cli.py
Generates JSON-LD context for provenance objects.
(closes #316)
=> cli: show context

Pipfile.lock, renku/cli/_cwl.py, setup.py
=> setup: unpin cwltool

renku/api/repository.py, renku/cli/_graph.py, renku/models/provenance/activities.py, renku/models/provenance/qualified.py, tests/test_cli.py
Link files to input directories.
=> models: discover files in input directories

docs/cli.rst, renku/api/repository.py, renku/cli/__init__.py, renku/cli/_docker.py, renku/cli/notebooks.py, renku/cli/pull.py, renku/models/_datastructures.py, renku/models/cwl/parameter.py, renku/models/cwl/process.py
Adds a CLI command to pull files from LFS. It follows the symlinks and goes into the submodules as necessary. 
addresses  #332 
closes https://github.com/SwissDataScienceCenter/renku/issues/452
New feature (non-breaking change which adds functionality)
- I have read and understood the **CONTRIBUTING** document.
- I have performed a self-review of my own code.
- I have signed and sent the [CLA document]
=> cli: add simple pull command for getting LFS data

renku/models/provenance/expanded.py
=> models: fix prov namespace

renku/api/repository.py, tests/test_cli.py
Fixes #342 
*Bug fix* (non-breaking change which fixes an issue)
=> lfs: make directory in gitattributes recursive

renku/cli/_ascii.py, renku/cli/_format.py, renku/cli/_graph.py, renku/cli/show.py, renku/models/cwl/command_line_tool.py, renku/models/provenance/activities.py, renku/models/provenance/entities.py, renku/models/provenance/qualified.py, tests/test_cli.py
Makes sure the run command works with deep output directories.
(addresses #336)
=> cli: fix run with subdirs

Pipfile.lock, setup.py
Fixes security issue in `requests` library.
=> Pipfile: security update for requests

conftest.py, renku/api/repository.py, renku/cli/_ascii.py, renku/cli/workflow.py, renku/errors.py, renku/models/_datastructures.py, renku/models/refs.py, tests/cli/test_refs.py
Allows adding names to CWL files.
=> cli: named workflows

.travis.yml, docs/conf.py, renku/__init__.py, renku/__version__.py, renku/cli/_git.py, renku/cli/_version.py, setup.py
Release development version on every commit to master.
=> setup: use setuptools_scm for version detection

renku/cli/_graph.py, renku/cli/log.py, renku/models/_git.py, tests/cli/test_range_queries.py
Supports range filter on `renku log`.
(closes #363)
=> cli: support range filter on log

renku/cli/run.py
=> docs: rephrase I/O paths detection

renku/models/_git.py, setup.py, tests/models/test_git.py, tests/test_cli.py
clean up and provide tests for git repo URL regex. 
closes #365
=> update git href regex

.dockerignore, CHANGES.rst, Dockerfile, README.rst, brew.py
- improves docker and brew
- adds release notes
=> release: v0.3.0

README.rst
Fixes `python setup.py check --restructuredtext`
=> docs: fix headers in readme

renku/models/_git.py, tests/models/test_git.py
closes #374
- Bug fix (non-breaking change which fixes an issue)
- I have added tests to cover my changes.
- I have **NOT** removed any existing tests.
- I have run ``./run-tests.sh`` locally.
=> models: fix git regex

CHANGES.rst, renku/models/_git.py, tests/models/test_git.py
Bug fixes for v0.3.x.
---
```
git fetch upstream
git checkout -b maint-0.3 upstream/maint-0.3
git checkout master
git merge --no-ff maint-0.3
git push upstream master
```
=> release: v0.3.1

.travis.yml, brew.py, docs/cli.rst, renku/cli/__init__.py, renku/cli/storage.py
Renames `pull path` to `storage pull`.
=> cli: pull to storage

renku/api/_git.py, renku/cli/_options.py, renku/cli/init.py, renku/cli/run.py, renku/errors.py, tests/cli/test_init.py, tests/test_cli.py
Uses branches for ``renku init --force``.
=> cli: init force in branches

renku/api/_git.py, renku/api/datasets.py, renku/cli/dataset.py, renku/errors.py, tests/cli/test_gitignore.py, tests/test_client.py
Verify that any file added to a dataset is in `.gitignore`.
Fixes #385
=> api: check gitignore with dataset add

Pipfile.lock, renku/_compat.py, renku/cli/__init__.py, renku/cli/_version.py, setup.py
Periodically checks for latest version for `renku` when executed from CLI.
=> cli: check for latest version

renku/cli/_exc.py
Do not prompt with redirected streams.
=> cli: do not prompt with redirected streams

renku/models/provenance/activities.py, renku/models/provenance/entities.py
* Addresses issue with commits editing multiple CWL files.
(closes #395)
* Exports merge commits for full lineage.  (addresses #370)
--
cc @LiliGasser @lusamino
=> models: export merge commits

renku/models/provenance/activities.py, renku/models/provenance/entities.py
* Renames CommitMixin._location to _project.
=> models: foaf:Project as dcterms:isPartOf

renku/cli/init.py, renku/cli/runner.py, tests/cli/test_init.py
* Ask user before overriding an existing file using `renku init`
or `renku runner template`.
(closes #406)
=> cli: ask before overriding existing files

renku/api/_git.py, renku/api/repository.py, renku/api/storage.py, setup.py, tests/cli/test_init.py, tests/models/test_git.py
=> api: worktree with lfs checkout

renku/cli/show.py, tests/cli/test_output_option.py, tests/cli/test_show.py
Support directories in `renku show outputs`
=> cli: show output directories

renku/cli/_format.py
Changes the `dot-full` log options to output a reduced rdf graph. The full graph is produced if `dot-debug` is used. 
- New feature (non-breaking change which adds functionality)
=> log: adding reduced dot format

renku/api/datasets.py, renku/cli/_checks/__init__.py, renku/cli/_checks/files_in_datasets.py, renku/cli/_checks/location_datasets.py, renku/cli/doctor.py
Adds check for discovering missing files listed in datasets.
(closes #305)
=> doctor: check missing files in datasets

renku/_compat.py, renku/api/datasets.py, renku/cli/dataset.py, renku/cli/migrate.py, setup.py, tests/test_cli.py
Changes dataset metadata path to use UUID instead of its name.
--
closes #417
=> feat(datasets): use uuid for metadata path

setup.py
Adds missing project URLs for nicer PyPI sidebar.
=> chore: add missing project urls

renku/cli/_checks/files_in_datasets.py
=> fix: removes typo causing wrong path resolution

renku/cli/dataset.py, renku/models/_tabulate.py, tests/test_cli.py
Display of headers on datasets list could be cleaner. Updated short_id to id and authors_csv to authors.
Fixes #424
=> chore(datasets): added remapping of headers in tabulate

conftest.py, pytest.ini
Includes conftest.py in pytest.ini.
=> style: improve forgotten conftest.py

renku/api/_git.py, renku/api/storage.py, renku/cli/rerun.py, renku/cli/run.py, renku/cli/storage.py, renku/cli/update.py
Simply pull all inputs from LFS.
closes #332
=> fix(cli): lazy lfs pull before run, rerun and update

renku/api/storage.py, renku/cli/__init__.py, renku/cli/migrate.py, renku/cli/move.py, renku/models/datasets.py, setup.py, tests/cli/test_move.py
Moves files and updates dataset metadata.
(closes #341)
--
@LiliGasser @nperraud
=> feat(cli): add mv command

.travis.yml, brew.py, renku/api/storage.py, renku/cli/__init__.py, renku/cli/migrate.py, renku/cli/move.py, renku/models/datasets.py, setup.py, tests/cli/test_move.py
Splits Travis CI to build stages.
(closes #433)
=> ci: split to build stages

docs/cli.rst, renku/cli/_exc.py, renku/cli/move.py, setup.py
Requires `SENTRY_DSN` variable to be set and `sentry-sdk` package to be installed.
=> perf: report exceptions to Sentry when configured

renku/cli/dataset.py, renku/models/_json.py, renku/models/_jsonld.py, renku/models/cwl/_ascwl.py, renku/models/datasets.py, tests/cli/test_datasets.py
Adds JSON-LD output format for datasets.
Fixes #426
=> feat(cli): configurable format of dataset output

renku/cli/_format/dataset_files.py, renku/cli/dataset.py, renku/models/datasets.py, tests/cli/test_datasets.py, tests/test_dataset.py
This PR adds ls-files command which will list all files with a given set of filters.
Fixes #446
=> feat(datasets): added ls-files command

.gitignore, renku/api/repository.py, renku/cli/_graph.py, renku/cli/runner.py, renku/cli/workflow.py, renku/models/provenance/__init__.py, renku/models/provenance/activities.py
Move `from_git_commit` function to `client.process_commit`
=> refactor(api): move from_git_commit to client.proces_commit

renku/api/datasets.py, renku/api/repository.py, renku/cli/_config.py, renku/cli/migrate.py, renku/cli/runner.py, renku/models/_jsonld.py, renku/models/cwl/_ascwl.py, renku/models/provenance/activities.py, tests/cli/test_output_option.py, tests/test_cli.py, tests/test_cwl.py, tests/test_dataset.py, tests/test_projects.py
=> fix: use safe_load for parsing yaml

conftest.py, tests/cli/test_datasets.py, tests/cli/test_gitignore.py, tests/cli/test_move.py, tests/cli/test_range_queries.py, tests/cli/test_refs.py, tests/cli/test_update.py, tests/test_cli.py
Use `assert CONST OP VALUE` consistently.
=> test: fix assert order to "constant cmp value"

renku/cli/_ascii.py, renku/cli/_format/graph.py, renku/cli/githooks.py, renku/cli/rerun.py, renku/models/_datastructures.py, renku/models/_jsonld.py, renku/models/datasets.py, run-tests.sh, setup.py, tests/models/test_git.py, tests/test_cli.py
Use `unify` tool for consistent quotes.
=> style(unify): use consistent style for string quotes

renku/api/datasets.py, renku/cli/_format/datasets.py, renku/cli/dataset.py, tests/cli/test_datasets.py
Load datasets from a specific commit.
=> feat(api): list datasets from a commit

renku/cli/dataset.py, tests/cli/test_datasets.py
* Uses arguments to define datasets filter.
=> refactor: filter dataset files by names

renku/api/datasets.py, renku/cli/dataset.py, renku/models/datasets.py, tests/cli/test_datasets.py
Adds unlink command. 
fixes #447
=> feat(cli): add dataset unlink command

README.rst, brew.py
Adds missing dependency for Linux brew.
=> build(brew): fix build of lxml from source on Linux

docs/cli.rst, renku/api/_git.py, renku/api/datasets.py, renku/cli/__init__.py, renku/cli/move.py, renku/cli/remove.py, renku/models/datasets.py, tests/cli/test_remove.py
* Automatically update affected metadata files.
=> feat(cli): add rm command

README.rst
=> Add pull reminder badge to README

renku/api/datasets.py, renku/cli/dataset.py, tests/cli/test_datasets.py
Adds dataset rm command.
closes #418
=> feat(cli): add dataset rm command

renku/cli/dataset.py
=> docs(datasets): add missing commands to docs

docs/api.rst
Remove outdated sentence in the documentation.
=> docs(api): remove old mention about REST

renku/api/datasets.py, renku/api/repository.py, renku/cli/dataset.py, renku/cli/move.py, renku/cli/remove.py, renku/models/_jsonld.py, renku/models/_locals.py, renku/models/datasets.py
=> refactor(models): simplify serialization to YAML

renku/cli/_checks/references.py, renku/cli/dataset.py, renku/models/refs.py, tests/cli/test_datasets.py
=> fix(cli): add check of missing references

renku/models/cwl/command_line_tool.py, tests/test_cwl.py
=> fix(cwl): detect script as input parameter

renku/api/datasets.py, renku/cli/_ascii.py, renku/cli/_graph.py, renku/cli/migrate.py, renku/cli/workflow.py, renku/models/cwl/parameter.py, renku/models/provenance/qualified.py, renku/models/refs.py, setup.py
CI is failing due to update on our code formatter. 
This PR should fix:
* CI to run again
* Security problem reported by github
=> fix(deps) updated dependencies

.gitignore, renku/cli/_providers/__init__.py, renku/cli/_providers/api.py, renku/cli/_providers/doi.py, renku/cli/_providers/zenodo.py, renku/cli/dataset.py, setup.py, tests/cli/test_datasets.py
This PR adds new dataset command `import`. 
closes #507 
TODO: 
[ x ] Add version to name
[ x ] Remove tmpdirs from created datasets
[ x ] Reduce update rate on progress bar and track progress in MB's
[ x ] Fix progress bars in Windows shell
[ x ] Extract option should handle common tarballs
=> feat(datasets): import data from zenodo

renku/cli/dataset.py, tests/cli/test_datasets.py, tests/cli/test_gitignore.py, tests/cli/test_move.py, tests/cli/test_remove.py
=> fix: added check for overwriting datasets

.travis.yml, docs/models/datasets.rst, renku/api/datasets.py, renku/api/repository.py, renku/cli/_exc.py, renku/cli/_format/dataset_files.py, renku/cli/_format/datasets.py, renku/cli/_providers/__init__.py, renku/cli/_providers/doi.py, renku/cli/_providers/zenodo.py, renku/cli/dataset.py, renku/models/_jsonld.py, renku/models/datasets.py, renku/utils/__init__.py, renku/utils/doi.py, setup.py, tests/cli/test_datasets.py, tests/test_cli.py, tests/test_dataset.py
=> feat: integrate metadata from zenodo

renku/api/datasets.py, renku/cli/_format/datasets.py, renku/cli/dataset.py, renku/models/datasets.py, setup.py, tests/cli/test_datasets.py
=> feat: edit dataset metadata

README.rst
Documentation update for enabling external debugging.
=> docs: using ptvsd

renku/api/_git.py, renku/api/repository.py, renku/cli/_client.py, renku/cli/dataset.py, renku/errors.py, tests/cli/test_datasets.py
=> feat: added support for dataset commands on dirty repo

renku/api/client.py, renku/models/_datastructures.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
*  pydocstyle was updated a few days ago which is causing Travis to fail
*  refactored missing integration test
=> fix: refactored tests and docs to align with updated pydocstyle

.travis.yml, renku/api/storage.py, renku/cli/move.py, renku/cli/remove.py, renku/cli/rerun.py, renku/cli/run.py, renku/cli/update.py, renku/errors.py, setup.py, tests/test_cli.py
* fixes accidental removal of --no-external-storage check on run command
* refactors storage API to be more secure and clean
* prevents unnecessary computations inside click commands
* fixes the tests back to the expected behavior
closes: #588
=> fix: ensure external storage is handled correctly

tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
=> tests: cleanup of test dataset import

.travis.yml, setup.py
This reverts the automatic versioning to follow the `<sem-ver>-devX` convention to be compatible with PyPI.
=> build: use simplified version for pypi compatibility

renku/models/_jsonld.py, renku/utils/datetime8601.py, tests/cli/test_datasets.py
* Ensures that datetime fields are serialized to isoformat
* Adds tests to check correct serialization
closes #627
=> fix: fixed serialization of datetime to iso format

Pipfile.lock, setup.py
Github did security scan on our repo and found a security problem in werkzeug package. This PR updates the package to suggested version.
=> fix: security update

README.rst
minor update to repo's readme file
=> docs: fix broken readme link

tests/cli/test_integration_datasets.py
Fixes broken test which got merged in #647
=> fix: fixes broken integration test

conftest.py, renku/models/datasets.py, renku/models/provenance/agents.py, tests/test_dataset.py, tests/test_serialization.py
closes #654 
closes #638 
Also adds some basic sanity checks for dataset (de)serialization.
=> fix user-related metadata

renku/cli/dataset.py
closes #674 
Adds documentation of import and export command
=> feat: import export documentation

.github/workflows/test.yml, .travis.yml, renku/models/projects.py, renku/utils/datetime8601.py, run-tests.sh, setup.py
Closes #678 
Removes need for pytz from dataset migration relevant code.
Updates run-tests.sh to test docs and unit-tests separately, reducing the potential for depedency leakage into unit tests
Updates travis-ci and github actions for the updated run-tests.sh script
=> fix: hotfix migration timezones

CHANGES.rst
Update changes.rst for `v0.6.0`
=> chore: update changes.rst

renku/data/gitignore.default
Adds `.renku/tmp` to project's `.gitignore`. This directory is used to temporary save list of input and output files that are programatically generated by a script.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/705
=> 705 update gitignore

renku/core/management/git.py, tests/cli/test_datasets.py
There was a check to make sure only files that exist get added to ggit, which is not the case for files that were deleted. Now deleted files get added despite this check, though the check remains in place for all other changes.
Fixes #708
=> fix: fixes bug with deleted files not getting committed

tests/cli/test_integration_datasets.py
Fix integration tests for https://github.com/SwissDataScienceCenter/renku-python/issues/681
=> fix: integration tests

CHANGELOG.md, MANIFEST.in, Pipfile, Pipfile.lock
* generates changelog for the new release
* updates stale dependencies from #699
=> chore: release preparation

renku/core/models/jsonld.py
=> fix: Fixes jsonld issue when importing from dataverse

conftest.py, renku/cli/exception_handler.py, renku/core/commands/graph.py, renku/core/management/repository.py, renku/core/models/datasets.py, renku/core/models/provenance/activities.py, renku/core/models/provenance/agents.py, setup.py
Refactor `Creator` and `Person` to avoid code duplication and allow consistent metadata. 
addresses #793
includes changes from #783 to allow tests to pass
=> fix: make datasets.Creator a subclass of Person

conftest.py, renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/errors.py, renku/core/management/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py
When adding file to a non-existing dataset, this PR prevent implicit creation of the dataset. User must pass `--create` for creation of a non-existing dataset.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/688
=> feat: do not create dataset implicitly

renku/core/commands/graph.py, renku/core/models/creators.py, renku/core/models/provenance/__init__.py, renku/core/models/provenance/agents.py, tests/core/models/test_projects.py
This PR refactors `Creator` to be a subclass of `Person`. (closes #793)
=> make Creator a subclass of Person

CHANGES.rst
Prep changelog for new release.
=> chore: update changelog

renku/core/models/provenance/activities.py
=> fix: initialize Activity with Commit post-init

conftest.py, renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/commands/providers/dataverse.py, renku/core/commands/providers/zenodo.py, renku/core/management/datasets.py, renku/core/models/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
Various bug fixes regarding dataset imports (`--extract` won't add extracted files to metadata, ...). It also refactors the import logic. 
~~Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/839~~
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/855
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/858
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/866
=> fix: various bugs in dataset import

.travis.yml
skip CI for pushed branches on PRs
=> build: do not do branch build on PRs

.travis.yml
Fixes error in mac os x test configuration.
=> chore: fix mac os x tests

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/commands/format/dataset_files.py, renku/core/commands/format/datasets.py, renku/core/commands/format/tabulate.py, renku/core/models/datasets.py, renku/core/models/tabulate.py, renku/service/views/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
Minor fixes to dataset commands output. To address long output list, this PR adds a column selection option to `renku dataset` and `renku dataset ls-files` commands where user can use to show a selected list of properties. 
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/821
=> feat: improve dataset command output

.github/workflows/test_deploy.yml
some CI jobs are not being scheduled, possibly due to improper branch filtering.
=> chore: fix nested branch filtering

.mergify.yml
This change has been made by @rokroskar from https://mergify.io simulator.
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documention](https://doc.mergify.io/).
<br />
<br />
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR
- `@Mergifyio backports <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:
- look at your merge queues
- generate the Mergify configuration with the simulator.
Finally, you can contact us on https://mergify.io/
</details>
=> chore: mergify configuration update

.github/workflows/pipfile-update.yml
Adds an action to automatically update `Pipfile.lock` whenever `setup.py` changes.
=> chore: add action to update Pipfile

.github/workflows/test_deploy.yml
Adds an action to automatically cancel running workflow runs on the same branch.
=> chore: cleanup action

CHANGES.rst
=> build: Release v0.9.0

Pipfile
Enables test run without sourcing virtual environment.
```
pipenv run tests
```
=> feat: run tests via pipenv run commands

.github/workflows/test_deploy.yml
updates the main renku chart after successful chart build
closes #987
=> chore: automatically update the main chart

.github/workflows/automerge.yml, .github/workflows/pipfile-update.yml, .github/workflows/test_deploy.yml
automated updates of pipfiles are not triggering CI builds - this should fix it.
=> chore: fix bot commits

renku/core/commands/checks/migration.py, renku/core/commands/dataset.py, tests/cli/test_datasets.py
=> fix: enable dataset cmd in sub directories

Dockerfile.svc
Use the threaded gunicorn workers for handling concurrent requests.
=> chore: use gthread worker for better concurrency

renku/core/commands/dataset.py, renku/service/views/__init__.py, renku/service/views/datasets.py, tests/core/commands/test_dataset.py, tests/service/jobs/test_datasets.py, tests/service/views/test_utils.py
* Improves core list datasets 
* Improves core list files 
* Improves response serialization
* Adjusts tests
closes: #1022
=> fix: improved list datasets and files

Pipfile.lock, setup.py
Pins `gitdb` to avoid incompatibility with gitpython.
=> build: pin gitdb version

renku/core/commands/providers/dataverse.py, tests/core/commands/providers/test_dataverse.py
=> fix: fields with default need to come last

renku/service/cache/jobs.py, renku/service/serializers/jobs.py, renku/service/views/jobs.py, tests/service/views/test_jobs_views.py, tests/service/views/test_utils.py
=> feat(svc): adds job details endpoint

renku/service/cache/__init__.py, renku/service/entrypoint.py, renku/service/jobs/datasets.py, renku/service/views/decorators.py
Share same cache instance on service and workers.
=> fix: cache instance cleanup

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement_request.md, .github/ISSUE_TEMPLATE/proposal.md
=> docs: added github templates for proposal and improvement requests

.github/workflows/test_deploy.yml
Replaces several steps of the publish action with a generic Docker action
from the main renku repo. 
Successful run here: https://github.com/SwissDataScienceCenter/renku-python/runs/456554251?check_suite_focus=true
Fixes #1029
=> build: use generic action for component update

renku/service/jobs/datasets.py, tests/service/jobs/test_datasets.py
=> chore(service): fix commit message on dataset import

renku/service/jobs/datasets.py, tests/service/jobs/test_datasets.py
=> chore(service): fixes for junk & missing uri dataset imports

renku/cli/show.py, tests/core/commands/test_cli.py
=> fix(cli): consistenly show correct contexts

README.rst
updates CI badge to show github actions status.
=> chore: Update README.rst

renku/core/management/datasets.py, renku/service/jobs/datasets.py, tests/service/jobs/test_datasets.py
=> chore(service): decoupled state changes from core progress bar

Pipfile.lock, renku/cli/dataset.py, renku/core/management/datasets.py, setup.py, tests/cli/test_integration_datasets.py
Now, you can use wildcards when selecting which files to be added from a git repo:
```
renku dataset add my-dataset -s notebooks/**/*py -s notebooks/*renku https://github.com/SwissDataScienceCenter/r10e-ds-py.git
```
=> feat(dataset): wildcard support when adding data from git

CHANGES.rst
=> chore: update changelog for 0.10.0

renku/core/management/datasets.py, tests/cli/test_integration_datasets.py
=> feat(datasets): add files from dropbox

conftest.py, renku/cli/init.py, renku/core/commands/init.py, tests/cli/test_errors.py, tests/cli/test_init.py, tests/core/commands/test_cli.py, tests/core/commands/test_init.py
Restyle `renku init` options to make them more intuitive and user friendly.
The list of changes is available here #1125
Fixes #1125
=> feat: renku init options refactor

renku/core/commands/graph.py, tests/cli/test_update.py
Fixes a regression in which absolute paths are generated in workflows.
=> fix(core): directory input regression

renku/core/commands/dataset.py, tests/cli/test_integration_datasets.py
Imported dataset's URL was not set correctly.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1102
=> fix(dataset): wrong url when importing with DOI

MANIFEST.in, helm-chart/renku-core/templates/deployment.yaml, renku/service/config.py, renku/service/entrypoint.py, renku/service/logger.py, renku/service/logging.yaml, renku/service/scheduler.py, renku/service/worker.py
closes: #1013
This PR needs to be merged after #1140 due to the need to add additional logging in those refactored jobs.
=> chore(service): added additional logging

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, tests/cli/test_datasets.py
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1151
=> feat(dataset): remove --link flag

renku/service/serializers/datasets.py, renku/service/views/datasets.py, tests/service/views/test_dataset_views.py
=> feat(datasets): specify title on dataset creation

renku/core/errors.py, renku/core/management/datasets.py, tests/cli/test_datasets.py
Succeed when adding ignored files to a dataset and print a warning that those files are not added.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1180
=> feat(dataset): no failure when adding ignored files

renku/core/commands/clone.py, renku/core/management/clone.py, tests/cli/test_integration_datasets.py
=> feat: project clone API support for revision checkout

conftest.py
=> test: branch cleanup after run

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/commands/format/datasets.py, renku/core/management/datasets.py, renku/core/models/datasets.py, tests/cli/test_datasets.py
Keywords for datasets when creating/editing.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1150
=> feat(dataset): keywords in metadata

MANIFEST.in, Pipfile.lock, run-tests.sh, setup.py
This PR fixes our tests runner so it works with the latest version of check manifest.
=> chore: check manifest update

tests/service/views/test_cache_views.py
sets missing integration test marks
=> chore: set missing integration marks

CHANGES.rst, Pipfile.lock, setup.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_init.py
Preparation for release v0.10.4.
=> chore: prep release v0.10.4

renku/cli/dataset.py
=> docs(dataset): added docs for dataset revision usage

renku/cli/dataset.py
=> chore(dataset): consistent output across dataset commands

renku/service/entrypoint.py
This PR sorts the service endpoints in documentation and adds missing ones.
=> docs(service): added missing docs for service endpoints

conftest.py, renku/service/entrypoint.py, renku/service/serializers/cache.py, renku/service/views/cache.py, tests/service/views/test_cache_views.py
=> feat(service): added endpoints to execute all migrations on a project

conftest.py, renku/cli/__init__.py, renku/cli/dataset.py, renku/cli/log.py, renku/cli/move.py, renku/cli/rerun.py, renku/cli/run.py, renku/cli/show.py, renku/cli/status.py, renku/cli/update.py, renku/cli/workflow.py, renku/core/commands/client.py, renku/core/commands/config.py, renku/core/commands/dataset.py, renku/core/commands/migrate.py, renku/core/management/migrate.py, tests/cli/test_migrate.py
Check for migration requirements in core instead of CLI. This provides a finer-grain control over the migration checking and also enables it for service commands.
Required for https://github.com/SwissDataScienceCenter/renku-python/issues/1302
=> feat(core): migration check in core

conftest.py, renku/core/commands/dataset.py, renku/service/entrypoint.py, renku/service/serializers/datasets.py, renku/service/views/datasets.py, tests/service/views/test_dataset_views.py
=> feat(service): adds endpoints for unlinking files from a dataset

renku/core/commands/migrate.py, renku/service/serializers/cache.py, renku/service/views/cache.py, tests/service/views/test_cache_views.py
=> feat(service): adds endpoint for explicit migrations check

renku/service/cache/projects.py, renku/service/errors.py, renku/service/views/datasets.py, tests/service/test_exceptions.py, tests/service/views/test_dataset_views.py
=> chore(service): raise correct exception on missing reference

renku/core/commands/providers/doi.py
=> fix(core): Add copright to DOI data

.github/workflows/test_deploy.yml
Disables integration tests on PRs
=> chore: Disable IT on PRs (for now)

renku/core/commands/providers/dataverse.py
Dataverse changed their publishing process to be async, now returning a 202 status code with `WORK IN PROGRESS`. I added the status code and fixed error messaging if `message` is not present in a response
=> fix(core): Fix dataverse publish

renku/service/serializers/headers.py
If renku fullname or email header is passed as base64, we will try to decode them if not we just use the raw value.
=> feat: decode base64 headers

renku/core/commands/format/graph.py, renku/core/models/workflow/run.py
Closes #1459 
Fixes dot output and OrderedSubprocess ids
=> fix: working dot output for new workflow code

Pipfile.lock, setup.py
Combines 
https://github.com/SwissDataScienceCenter/renku-python/pull/1473
https://github.com/SwissDataScienceCenter/renku-python/pull/1472
https://github.com/SwissDataScienceCenter/renku-python/pull/1471
https://github.com/SwissDataScienceCenter/renku-python/pull/1470
https://github.com/SwissDataScienceCenter/renku-python/pull/1466
https://github.com/SwissDataScienceCenter/renku-python/pull/1465
=> chore: update dependencies

renku/service/serializers/jobs.py, renku/service/views/cache.py, renku/service/views/datasets.py, renku/service/views/decorators.py, run-tests.sh
Adds flake8 tests since Black doesn't cover everything.
=> chore: add Flake8 test

renku/core/management/datasets.py, renku/core/models/calamus.py, renku/core/models/datasets.py, renku/core/models/provenance/agents.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py, tests/core/commands/test_serialization.py
Flattened JSON-LD for dataset's metadata.
An issue was Person with the same email but different names/affiliation that would create a list for those properties in the flattened JSON-LD. In such cases, this PR only loads the element in the list because I did not want to change the @id field to be something other than email.
Fixes #1253
=> feat(dataset): flattened JSON-LD metadata

Pipfile.lock, renku/core/management/git.py, setup.py
Removes dependency on `gitdb` from `renku-python`.
Fixes #1502
=> chore(core): remove dependency on gitdb/gitdb2

renku/core/commands/providers/doi.py, renku/core/errors.py, tests/core/commands/providers/test_dataverse.py, tests/service/jobs/test_jobs.py
closes: #1428
closes: #1430 
#1430 issue was also partially addressed in #1492, this PR adds additional test and closes that issue.
=> chore: adds custom exception handling on doi serialization

renku/core/commands/dataset.py, renku/core/management/datasets.py, tests/service/jobs/test_datasets.py
=> chore: follow redirects

renku/core/commands/dataset.py
Change to follow redirect urls broke `doi:...` import
=> fix(core): fixes doi: import

renku/core/models/provenance/activities.py
Persist workflow subprocesses.
=> chore(workflow): persist workflow subprocesses

CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: prep release v0.11.2

.github/workflows/pipfile-update.yml
fixes repeat pipfile lock updates due to hashes being non-deterministic
=> chore: fix repeat pipfile lock updates

renku/cli/show.py, tests/cli/test_show.py
Detailed output for `renku show inputs/outputs`
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/428
=> feat(cli): verbose output for renku show

renku/service/controllers/version.py, renku/service/entrypoint.py, renku/service/serializers/version.py, renku/service/views/version.py, tests/service/views/test_version_views.py
=> feat(service): adds version endpoint

renku/core/management/migrations/m_0005__2_cwl.py
makes path for id calculation relative instead of absolute.
=> fix(core): make Run migration ids unique by relative path instead of absolute

CHANGES.rst, helm-chart/renku-core/Chart.yaml, renku/core/management/migrate.py, renku/core/management/migrations/m_0005__2_cwl.py, tests/cli/test_migrate.py
=> fix(core): fix project migration getting overwritten with old metadata 

conftest.py, tests/cli/test_init.py, tests/core/commands/test_cli.py, tests/core/commands/test_init.py, tests/service/views/test_templates_views.py
Template and init tests cleanup.
* move template and init related costants and commands to fixtures
* updated and cleanup test affected by the aforementioned changes
fix #1290
=> fix: template test cleanup

renku/service/views/jobs.py, renku/service/worker.py, tests/service/jobs/test_datasets.py
=> chore(service): disable argument logging on workers

CHANGES.rst, helm-chart/renku-core/Chart.yaml
Release change-log and chart update
=> chore: release v0.11.5

renku/core/commands/dataset.py, renku/core/models/datasets.py, tests/cli/test_integration_datasets.py
Fix updating of renku datasets.
Fixes #1615
=> fix(dataset): set isBasedOn for renku datasets

CHANGES.rst, helm-chart/renku-core/Chart.yaml
Cherry-picked from release branch
=> chore: update changelog and chart for 0.11.6

conftest.py, renku/service/cache/jobs.py, renku/service/controllers/api/mixins.py, renku/service/controllers/datasets_add_file.py, renku/service/controllers/datasets_create.py, renku/service/controllers/datasets_import.py, renku/service/controllers/datasets_remove.py, renku/service/serializers/datasets.py, renku/service/views/datasets.py, renku/service/views/decorators.py, tests/service/jobs/test_datasets.py, tests/service/views/test_dataset_views.py
=> refactor(datasets): create, remove, import, add file datasets controllers

renku/core/models/calamus.py, renku/core/models/datasets.py, tests/cli/test_integration_datasets.py
Fixes a bug where dataset deserialization fails after adding multiple copies of the same file from a git repo.
Fixes #1577
=> fix(dataset): error when adding same file multiple times

CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: prep release v0.12.0

docs/api.rst, docs/gensidebar.py, docs/introduction.rst, renku/api/__init__.py, renku/api/models/dataset.py, renku/api/models/project.py, renku/api/models/run.py, renku/cli/rerun.py, renku/cli/update.py, renku/core/models/cwl/command_line_tool.py, renku/core/models/cwl/parameter.py, renku/core/models/provenance/activities.py, renku/core/models/workflow/converters/cwl.py, renku/core/models/workflow/parameters.py, renku/core/models/workflow/run.py, renku/data/shacl_shape.json, tests/api/test_run.py, tests/cli/test_indirect.py, tests/core/commands/test_cwl.py
Documentation for API.
Allows defining run parameters for workflows.
Fixes #1560
=> feat(api): parameters

.dockerignore, Dockerfile.svc, Pipfile.lock, renku/service/config.py, setup.py
* fixes #1743 by saving the requirements file in a temporary directory instead of in the repository directory.
* refactors the service requirements in setup.py so they are not installed in the CLI
* side benefit - runs the app as a non-privileged user.
=> chore: install container w/o dirty repo; run as non-root

renku/service/views/decorators.py
Logs current working directory on redis exceptions to help debug issues with intermittent `read_template_manifest` problems
=> chore: add cwd to sentry context on redis exceptions

renku/data/pre-commit.sh, tests/cli/test_datasets.py
=> feat(cli): automatically track files in git-lfs if necessary

conftest.py, renku/service/config.py, tests/service/views/test_cache_views.py
Support for decompressing gzip files after upload.
Fixes #1776
=> feat(service): gzip decompression support

Pipfile.lock, renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/models/datasets.py, renku/service/serializers/datasets.py, setup.py, tests/cli/test_datasets.py
Produces output like
```
$ renku dataset show testset
Testing Dataset
---------------
╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                     subtitle                                                      ║
╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
even supports markdown and lists:
• entry1
• entry2
Name: testset
Created: 2020-12-09 14:45:50.728529+00:00
Creator(s): Andi Bleuler <a@bleuler.com>
```
Closes #511
=> feat(cli): add dataset show command

docs/commands.rst, renku/cli/clone.py
Docs for `renku clone`. Changes an option to pull LFS data by default.
Fixes #1673
=> docs(cli): renku clone

renku/core/errors.py, renku/core/management/storage.py
=> fix(core): output git lfs error messages when there is an error

renku/cli/init.py, renku/cli/migrate.py, renku/cli/utils/callback.py, renku/core/commands/init.py, renku/core/commands/migrate.py, renku/core/management/migrate.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/models/git.py, renku/core/utils/communication.py, renku/service/controllers/cache_migrations_check.py, renku/service/jobs/project.py, renku/service/utils/callback.py, tests/cli/test_migrate.py, tests/service/controllers/utils/test_remote_project.py
Shows a progress report when migrating workflows and makes pre-processing CWL files faster by traversing git history once.
Fixes #1837
=> refactor(core): workflow migration speedup and progress feedback

conftest.py, renku/core/management/migrations/m_0005__2_cwl.py
Add a cache to speed up migrations and fixes some migration bugs.
Fixes #1852
=> feat(core): cache for workflow migrations

renku/cli/save.py, renku/core/commands/save.py, renku/core/management/git.py, renku/core/management/storage.py, tests/cli/test_save.py
Fixes issue with getting staged paths and also dealing with deleted&staged files in `renku save`
=> fix(core): fix renku save with deleted files

Pipfile.lock, conftest.py, renku/service/serializers/headers.py, setup.py, tests/service/views/test_cache_views.py, tests/service/views/test_jobs_views.py
=> chore: update pyjwt to 2.0.0

.github/workflows/acceptance-tests.yml, .github/workflows/test_deploy.yml
Updates the acceptance tests to run via `helm`.
/deploy
=> chore: update acceptance tests for running helm tests

renku/service/serializers/cache.py, renku/service/serializers/common.py, renku/service/serializers/datasets.py
=> refactor: prevent leaks of remote_branch in responses

renku/service/serializers/cache.py
=> fix: correctly handle ref on project.clone

renku/cli/exception_handler.py, renku/cli/graph.py, renku/cli/utils/callback.py, renku/core/commands/dataset.py, renku/core/incubation/graph.py, renku/core/management/datasets.py, renku/core/models/datasets.py, renku/core/models/provenance/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
Use new metadata in `graph dataset create` and `graph dataset add` commands.
Fixes #1735
=> feat(dataset): dataset create and add using new metadata

renku/core/commands/save.py, renku/core/commands/update.py, renku/core/management/datasets.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/management/storage.py, renku/core/models/cwl/command_line_tool.py, renku/core/utils/git.py
Split argument list for git commands.
Fixes #1880
=> fix(core): split git arguments list

conftest.py, renku/core/commands/providers/renku.py, renku/core/management/datasets.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/management/repository.py, renku/core/utils/migrate.py, renku/core/utils/urls.py, tests/cli/test_datasets.py
Reads and includes an OAuth token when querying KG for dataset imports.
Fixes #1854
=> feat(dataset): oauth authentication for KG access

renku/core/management/datasets.py, renku/core/models/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py
Allow more characters in generated names for imported datasets.
Fixes #1698
=> feat(dataset): improve naming for imported datasets

renku/core/incubation/graph.py, renku/core/management/migrations/m_0003__2_initial.py, renku/core/management/migrations/m_0008__dataset_metadata.py, renku/core/models/calamus.py, renku/core/models/provenance/activity.py, renku/core/models/workflow/dependency_graph.py, renku/core/utils/communication.py
Various fixes in graph generation.
Fixes #1933
=> feat(core): error-resilience in new graph generation

CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: release v0.14.0

.github/workflows/acceptance-tests.yml, .github/workflows/automerge.yml, .github/workflows/test_deploy.yml
Pins workflow cleanup action to v0.3.0
=> chore: pin workflow cleanup action

README.rst
=> chore: add prerequisites to readme

conftest.py, helm-chart/renku-core/values.yaml, renku/service/logger.py, renku/service/scheduler.py, tests/service/fixtures/service_scheduler.py, tests/service/scheduler/test_scheduler.py
=> chore: update scheduler intervals and logging redirect

Dockerfile.svc, renku/core/commands/save.py
Adds proper error handling if pushing the temporary branch after a failed push to a protected branch fails.
/deploy
=> fix(core): Add error handling if push of temporary branch fails

Pipfile.lock, setup.py
=> chore: update pyyaml

renku/core/management/clone.py, renku/service/serializers/cache.py, renku/service/serializers/templates.py, tests/cli/test_integration_cli.py
Fixes project clone to correctly checkout the remote ref.
/deploy
=> fix(service): fix project_clone with git ref specified

renku/cli/migrate.py, renku/core/commands/migrate.py, tests/cli/test_migrate.py
=> feat(cli): support template and docker migration

renku/core/incubation/graph.py, renku/core/models/provenance/activities.py
Error-resilience when processing git history involves deleted files.
Fixes #1995
=> fix(core): no failure when processing git history for deleted files

renku/core/models/cwl/annotation.py, renku/core/models/provenance/activities.py, setup.py
Fixes #1952
depends on https://github.com/SwissDataScienceCenter/calamus/pull/58
=> fix(core): Fix annotations serialization in ProvenanceGraph

renku/core/models/workflow/dependency_graph.py, renku/core/models/workflow/parameters.py, renku/core/models/workflow/plan.py, renku/data/new_graph_shacl_shape.json, renku/data/shacl_shape.json, tests/cli/test_run.py
Adds `name` and `description` to `CommandParameter` and it's subclasses.
Fixes #2035
=> feat(workflow): naming metadata for command parameters

CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: release v0.15.0

.github/workflows/acceptance-tests.yml
Acceptance test screenshots were not getting uploaded properly because of a missing parameter. 
/deploy
=> chore(tests): specify acceptance test file path

CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: release v0.15.1

renku/core/commands/run.py, renku/core/commands/update.py, renku/core/incubation/graph.py, renku/core/management/repository.py, renku/core/management/storage.py, renku/core/models/entities.py, renku/core/models/provenance/activity.py, renku/core/models/provenance/parameter.py, renku/core/models/provenance/provenance_graph.py, renku/core/models/workflow/dependency_graph.py, renku/core/models/workflow/parameter.py, renku/core/models/workflow/parameters.py, renku/core/models/workflow/plan.py, renku/core/utils/urls.py, renku/data/new_graph_shacl_shape.json, tests/cli/test_run.py
Adds `ParameterValue` and it's subclasses to `Activity` when a command is run. Also creates equivalent classes for the new graph metadata instead of using those from the existing metadata (`Association`, `Usage`, `Generation`, `CommandParameter` and its subclasses). Some refactoring and addition of type hints.
Fixes #2036
=> feat(core): ParameterValue in provenance

tests/cli/test_integration_cli.py, tests/fixtures/config.py, tests/service/cache/test_cache.py, tests/service/controllers/utils/test_project_clone.py, tests/service/controllers/utils/test_remote_project.py, tests/service/fixtures/service_client.py, tests/service/jobs/test_jobs.py, tests/service/views/test_dataset_views.py
Moves IT repos to dedicated `renku-python-integration-tests` group
=> chore: move integration test repos

renku/data/pre-commit.sh, tests/cli/test_datasets.py
=> fix(cli): Fix Git LFS autocommit hook not committing new pointer files

.github/workflows/test_deploy.yml, Dockerfile.cli, Dockerfile.svc, Makefile
Fixes the image build; also adds image building to the CI on pushes so broken builds don't sneak by in the future.
=> chore: fix image build and test in ci

renku/core/commands/init.py, tests/core/commands/test_init.py
=> fix(core): checkout template repository by revision

.github/workflows/test_deploy.yml, .github/workflows/test_publish.yml
removes the release action as we create releases manually
=> chore: remove release action

renku/service/controllers/datasets_create.py, renku/service/controllers/datasets_edit.py, renku/service/controllers/utils/__init__.py, renku/service/controllers/utils/datasets.py, renku/service/serializers/datasets.py, tests/service/views/test_dataset_views.py
=> fix(service): handle uploaded images in datasets.edit

renku/api/models/dataset.py, tests/api/test_dataset.py
=> feat(api): re-add api datasets commands using new database backend

.github/workflows/test_deploy.yml, CONTRIBUTING.rst, setup.py
Phase out support for python 3.6 as it nears its end of life this december.
=> chore: remove python 3.6 support, add python 3.9 support

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, renku/core/metadata/database.py, renku/core/models/dataset.py, renku/core/models/provenance/annotation.py, renku/service/controllers/datasets_create.py, renku/service/controllers/datasets_edit.py, renku/service/serializers/datasets.py, tests/cli/test_datasets.py, tests/service/views/test_dataset_views.py
=> feat(core): add custom dataset metadata

renku/data/shacl_shape.json, tests/service/views/test_templates_views.py
adds renku:hasDataset, renku:hasPlan, renku:hasActivity to Project SHACL shape
=> fix(core): add missing project properties to SHACL file

.github/workflows/test_deploy.yml, .github/workflows/test_publish.yml
this is a temporary fix until a proper fix is done for `git-lfs` v3.0.0 major release
=> fix(core): pin git-lfs on macos to 2.13.3

.dockerignore
=> fix(service): fix git config getting included in service images

docker-compose.yml, renku/service/controllers/version.py, renku/service/serializers/version.py, renku/service/views/api_versions.py, renku/service/views/apispec.py, renku/service/views/cache.py, renku/service/views/config.py, renku/service/views/datasets.py, renku/service/views/graph.py, renku/service/views/jobs.py, renku/service/views/project.py, renku/service/views/templates.py, renku/service/views/version.py, tests/service/views/test_version_views.py
=> feat(service): add API versioning on service

setup.py
=> chore: bump pyshacl to 0.17.2

renku-release-notes-1.0.0.md
Address review comments for loop documentation in the 1.0.0 release notes.
=> chore(docs): workflow loop documentation

renku/core/management/migrations/m_0005__2_cwl.py, renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/management/migrations/models/v9.py, renku/core/metadata/repository.py, renku/core/utils/git.py, setup.py, tests/core/metadata/test_repository.py
Fix an issue with workflow migrations. Add error-resilience.
=> feat(core): error-resilience in workflow migrations

renku/core/commands/run.py, renku/core/management/datasets.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/management/migrations/models/v9.py, renku/core/management/storage.py, renku/core/management/workflow/plan_factory.py, renku/core/metadata/repository.py, renku/core/models/dataset.py, renku/core/utils/urls.py, tests/core/commands/test_dataset.py
-  Various fixes in migrations
- Print warning messages only once for a pair of path and revision
=> fix(core): various migration issues

poetry.lock, pyproject.toml, renku/core/metadata/database.py, renku/core/metadata/gateway/database_gateway.py
=> feat(core): turn on zstandard based compression

CHANGES.rst, build.py, helm-chart/renku-core/Chart.yaml
=> chore: release v1.0.0

renku/core/metadata/database.py, renku/core/metadata/immutable.py
`get_attribute` needs a module import for getting the attribute of the module. make sure that the module gets imported before getting the attribute
=> fix(core): import the component in database.get_attribute 

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, poetry.lock
=> chore: Release 1.0.1

renku/core/management/workflow/providers/toil.py
This fixes the execution of a workflow using toil, when the input of a workflow is a directory that contains directories as children.
=> fix(core): recurse input of workflows when using toil provider

.github/workflows/test_publish.yml
=> chore(core): switch to git flow

renku/core/commands/update.py, renku/core/management/workflow/converters/cwl.py, renku/core/models/workflow/parameter.py
=> fix(core): fix workflow iterate on composite plan with links

renku/service/controllers/cache_migrate_project.py
=> fix(service): fix cache.migrate not locking the project

renku/cli/workflow.py
=> docs: add YAML example for workflow execute and iterate

.github/workflows/test_deploy.yml, CHANGES.rst, helm-chart/renku-core/Chart.yaml
=> chore: release v1.0.2

renku/core/models/workflow/plan.py
=> fix(core): fix copying keywords of a plan

renku/data/shacl_shape.json, tests/cli/test_graph.py
=> fix(core): fix SHACL for Plan and CompositePlan

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml
Release v1.0.3
/deploy renku=1.0-next renku-graph=development renku-ui=master
=> chore: release v1.0.3

renku/core/management/migrate.py
=> fix(core): fix regex for matching migration script filename format

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/templates/configmap.yaml, helm-chart/renku-core/values.yaml
Port hotfix release to develop branch
=> hotfix(service): v1.0.4 unlimited file size in nginx config (#2609)

.github/workflows/test_deploy.yml
=> fix(core): Switch from RENKU_CI_TOKEN to RENKUBOT_GITHUB_TOKEN

poetry.lock, pyproject.toml, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/management/workflow/converters/cwl.py
=> fix(core): replace cwlgen with cwl-utils

poetry.lock, renku/core/commands/providers/renku.py
=> fix(core): fix file size in dataset imported from renku

renku/service/views/project.py, tests/service/views/test_project_views.py
=> fix(service): remove json requirement from project.lock_status

renku/core/management/datasets.py, tests/cli/test_integration_datasets.py
Fixes a remaining case from #1765
=> fix(dataset): use correct destination when adding from url

renku/core/management/migrations/models/v9.py, renku/core/management/migrations/utils/conversion.py, renku/core/models/dataset.py, renku/core/utils/urls.py
=> fix(core): avoid migration failure for invalid dataset names

helm-chart/renku-core/requirements.yaml, helm-chart/renku-core/templates/_helpers.tpl, helm-chart/renku-core/templates/deployment.yaml, helm-chart/renku-core/values.schema.json, helm-chart/renku-core/values.yaml, renku/service/cache/config.py, renku/service/jobs/queues.py
This is a PR that applies the same changes as #2696 to 0.16.4. It will result in a new version - 0.16.5.
NOTE: target branch is `0.16-lts` from there we can make a new release from 0.16.5.
=> fix: work with redis sentinel

renku/core/commands/workflow.py
=> fix(core): check workflow execute inputs

.github/workflows/test_deploy.yml, renku/service/views/version.py, tests/cli/test_init.py, tests/service/views/test_version_views.py
=> chore(service): rename /version to /apiversion

renku/cli/init.py, renku/cli/run.py, renku/cli/workflow.py
Fixes a few minor formatting bugs in the CLI docs.
=> docs(cli): fix formatting issues

CHANGES.rst, Makefile, docs/spelling_wordlist.txt, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, poetry.lock, renku/core/commands/checks/__init__.py, renku/core/commands/checks/activities.py, renku/core/commands/schema/activity.py, renku/core/commands/schema/parameter.py, renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/models/provenance/activity.py, renku/core/models/workflow/parameter.py, renku/data/shacl_shape.json, tests/cli/test_template.py
=> chore: release v1.1.1

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, renku/data/shacl_shape.json
=> chore: release 1.1.2

.github/workflows/test_deploy.yml
Fixes `update-develop-branch` action and replaces `DOCKER_*` secrets with `RENKU_DOCKER_*` ones
=> chore: fix CI

renku/core/management/migrations/m_0009__new_metadata_storage.py
Fixes migration of deleted datasets (they were previously not considered during migration).
fixes #2755
=> fix(core): fix migration of deleted datasets

.github/workflows/test_deploy.yml, CHANGES.rst, Makefile, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, renku/__init__.py, renku/core/commands/view_model/template.py, renku/core/management/template/template.py, renku/core/management/template/usecase.py, renku/core/models/template.py, renku/version.py, tests/cli/test_template.py, tests/fixtures/templates.py
Cherry picks https://github.com/SwissDataScienceCenter/renku-python/pull/2763 to fix template update check in the core service.
=> chore: release 1.1.3

poetry.lock, pyproject.toml
add `docker` python package as a hard requirement.
=> fix(core): add docker package as a hard requirement

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, renku/core/commands/view_model/activity_graph.py, renku/core/errors.py, renku/core/management/workflow/activity.py, renku/core/metadata/gateway/activity_gateway.py, tests/cli/test_workflow.py
=> chore: release 1.1.4

renku/core/management/workflow/plan_factory.py, tests/cli/test_rerun.py, tests/fixtures/repository.py
=> fix(core): correct CommandOutputs for outputs in subdirectories

docs/how-to-guides/hpc.rst, renku/core/commands/version.py, renku/core/management/workflow/providers/toil.py, tests/cli/test_workflow.py
Runs workflows using Docker with the Toil provider when proper setting is present in the execution's config file.
Fixes #2712
=> feat(workflow): docker container support for toil provider

docs/conf.py, renku/core/commands/format/dataset_files.py, renku/core/commands/format/dataset_tags.py, renku/core/commands/format/datasets.py, renku/core/commands/view_model/log.py, renku/core/management/dataset/datasets_provenance.py, renku/core/management/dataset/providers/zenodo.py, renku/core/management/interface/dataset_gateway.py, renku/core/metadata/database.py, renku/core/metadata/persistent.py, renku/core/models/dataset.py, renku/core/utils/urls.py
=> fix(core): optimize imports

renku/command/schema/dataset.py, renku/data/shacl_shape.json, renku/domain_model/provenance/activity.py, renku/version.py, tests/cli/test_graph.py
Adds more validation to our SHACL.
Removes outdated shapes.
Fixes #2760
=> chore(core): more SHACL validation

renku/ui/service/serializers/cache.py
=> fix(service): fix project_id not being autogenerated if missing in request schema

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, renku/data/shacl_shape.json
=> chore: release 1.2.2

renku/core/dataset/request_model.py, renku/core/migration/utils/conversion.py, renku/domain_model/dataset.py
=> fix(dataset): correct dataset image id after migration to v1.0.0

tests/core/plugins/test_session.py
adds tests for `renku session` sub-commands
=> fix(core): tests for renku session subcommands

start-telepresence.sh
Add support to telepresence v2 to the `start-telepresence.sh` script
=> chore: update telepresence script to support v2

renku/core/workflow/converters/cwl.py, renku/data/shacl_shape.json, tests/cli/test_workflow.py
=> fix(core): fix using float values in renku workflow iterate

renku/command/git.py, renku/command/options.py, renku/ui/cli/run.py, tests/cli/test_isolation.py
=> refactor(core): remove unused git isolation code

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml, renku/command/command_builder/command.py, renku/command/command_builder/repo.py, renku/command/config.py, renku/command/git.py, renku/command/options.py, renku/core/management/git.py, renku/core/workflow/converters/cwl.py, renku/data/shacl_shape.json, renku/infrastructure/repository.py, renku/ui/cli/run.py, renku/ui/service/gateways/gitlab_api_provider.py, tests/cli/test_config.py, tests/cli/test_isolation.py, tests/cli/test_workflow.py
=> chore: release v1.2.4

renku/ui/service/controllers/api/mixins.py
=> fix(service): raise exception correctly

renku/command/init.py, tests/service/views/test_templates_views.py
=> fix(service): create dummy metadata.yml when creating a project

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/values.yaml
=> chore: release 1.3.1

DEVELOPING.rst
Improves documentation on how to make a release.
=> chore: improve release documentation

renku/command/login.py, renku/core/dataset/providers/dataverse.py, renku/core/dataset/providers/olos.py, renku/core/dataset/providers/zenodo.py, renku/core/util/requests.py, tests/cli/fixtures/cli_gateway.py, tests/cli/test_login.py
Replace current custom CLI login flow implemented in the gateway with Device Auth Grant implemented in Keycloak.
Fixes #2636
=> feat(core): use oauth 2.0 device auth grant

renku/command/schema/plan.py, renku/command/view_model/plan.py, renku/command/workflow.py, renku/core/plugin/run.py, renku/core/workflow/plan_factory.py, renku/domain_model/workflow/plan.py, renku/ui/cli/utils/terminal.py, renku/ui/cli/workflow.py, tests/core/fixtures/core_plugins.py, tests/core/plugins/test_run.py
closes #2888 
Also removes some old plugin hooks, which aren't used by smartsky or mls anyways.
=> feat(cli): add custom metadata to Plan

renku/ui/cli/session.py
Minor typo -- probably a copy-paste leftover
=> style: fix typo in session open command description

.github/workflows/test_deploy.yml, conftest.py, poetry.lock, pyproject.toml, renku/command/graph.py, renku/domain_model/session.py, renku/infrastructure/gateway/database_gateway.py, run-tests.sh, tests/cli/test_graph.py, tests/cli/test_integration_datasets.py, tests/cli/test_service.py, tests/cli/test_session.py, tests/core/commands/test_cli.py, tests/core/commands/test_graph.py, tests/fixtures/domain_models.py, tests/fixtures/session.py
closes #3005 
closes #2174 
closes #2064
=> test: add tests for session, service and graph export

poetry.lock, renku/ui/service/cache/models/project.py, renku/ui/service/controllers/project_lock_status.py, renku/ui/service/serializers/project.py, tests/service/views/test_project_views.py
=> feat(svc): make timeout configurable on project.lock_status endpoint

.github/workflows/test_deploy.yml, docs/conf.py, docs/spelling_wordlist.txt, renku/command/dataset.py, renku/command/schema/activity.py, renku/core/dataset/dataset.py, renku/core/dataset/dataset_add.py, renku/core/dataset/providers/factory.py, renku/core/interface/storage.py, renku/core/migration/m_0009__new_metadata_storage.py, renku/core/util/os.py, renku/domain_model/dataset.py, renku/domain_model/entity.py, renku/domain_model/provenance/activity.py, renku/infrastructure/storage/base.py, renku/ui/cli/dataset.py, renku/version.py, tests/cli/test_integration_datasets.py
Adds a `mount` command to allow mounting data from S3 storages. 
Fixes #2974
=> feat(dataset): allow mounting s3 data

.github/dependabot.yml
=> chore(ci): use dependabot to track gh actions

.github/workflows/acceptance-tests.yml, .github/workflows/publish_shacl.yml, .github/workflows/test_deploy.yml, .github/workflows/test_publish.yml, poetry.lock, pyproject.toml
This PR was created by the Combine PRs action by combining the following PRs:
* #3122 build(deps): (deps): bump filelock from 3.6.0 to 3.8.0
* #3119 chore(deps): bump peter-evans/find-comment from 1 to 2
* #3118 chore(deps): bump rokroskar/workflow-run-cleanup-action from 0.3.0 to 0.3.3
* #3117 chore(deps): bump SwissDataScienceCenter/renku-actions from 1.0.0 to 1.1.0
* #3116 chore(deps): bump peter-evans/create-or-update-comment from 1 to 2
* #3115 chore(deps): bump actions/checkout from 2 to 3
=> Update combined dependencies

.github/workflows/labeler.yml, .github/workflows/publish_shacl.yml, .github/workflows/semantic_pr.yml, .github/workflows/test_deploy.yml, .github/workflows/test_publish.yml, pyproject.toml
This PR was created by the Combine PRs action by combining the following PRs:
* #3130 chore(deps): bump actions/setup-python from 1 to 4
* #3129 chore(deps): bump amannn/action-semantic-pull-request from 1.1.1 to 4.5.0
* #3128 chore(deps): bump actions/labeler from 2 to 4.0.1
* #3126 build(deps): (deps): bump calamus from 0.3.14 to 0.4.1
=> chore: update combined dependencies

.github/workflows/cheatsheet.yml
the id's were copy pasted but you can't have the same step id twice.
=> chore: fix cheatsheet action step ids

.vscode/settings.json, docker-compose.yml, poetry.lock, renku/command/run.py, renku/command/schema/composite_plan.py, renku/command/schema/plan.py, renku/command/view_model/agent.py, renku/command/view_model/composite_plan.py, renku/command/view_model/plan.py, renku/core/workflow/plan.py, renku/core/workflow/plan_factory.py, renku/domain_model/workflow/composite_plan.py, renku/domain_model/workflow/plan.py, renku/ui/cli/dataset.py, renku/ui/cli/run.py, renku/ui/cli/utils/terminal.py, renku/ui/cli/workflow.py, renku/ui/service/controllers/workflow_plans_list.py, renku/ui/service/entrypoint.py, renku/ui/service/serializers/workflows.py, renku/ui/service/views/api_versions.py, renku/ui/service/views/workflow_plans.py, tests/cli/test_run.py, tests/cli/test_workflow.py, tests/core/commands/test_graph.py, tests/fixtures/config.py, tests/fixtures/domain_models.py, tests/service/fixtures/service_integration.py, tests/service/fixtures/service_projects.py, tests/service/views/test_workflow_plan_views.py
=> feat(svc): add workflow_plans.list endpoint

renku/core/dataset/dataset.py, renku/core/project.py, renku/domain_model/project.py, renku/ui/cli/dataset.py, renku/ui/cli/project.py, renku/ui/service/controllers/datasets_edit.py, renku/ui/service/controllers/project_edit.py, renku/ui/service/serializers/datasets.py, renku/ui/service/serializers/project.py, tests/cli/test_datasets.py, tests/cli/test_project.py, tests/service/views/test_dataset_views.py, tests/service/views/test_project_views.py
closes #3120 
I was not able to figure out how to validate jsonld.
=> feat(cli): set list of custom metadata for project and dataset

renku/command/command_builder/command.py, renku/core/util/contexts.py, renku/domain_model/project_context.py, tests/core/test_project_context.py
=> fix(service): don't change working directory, as it isn't thread-safe

renku/ui/service/utils/squash.py
closes [#3138](https://github.com/SwissDataScienceCenter/renku-python/issues/3183)
=> fix(service): fixes core service not working with python 3.10

helm-chart/renku-core/templates/deployment.yaml, helm-chart/renku-core/values.yaml
goes together with https://github.com/SwissDataScienceCenter/renku/pull/2743
=> chore: make service account token mounting configurable

renku/command/view_model/composite_plan.py, tests/cli/test_workflow.py
=> fix(workflow): list composite plans

docs/spelling_wordlist.txt, poetry.lock, pyproject.toml, renku/command/command_builder/command.py, renku/core/plugin/dataset_provider.py, renku/core/plugin/session.py, renku/core/plugin/workflow.py, renku/core/util/git.py, renku/core/util/yaml.py, renku/core/workflow/converters/cwl.py, renku/core/workflow/plan.py, renku/core/workflow/providers/cwltool.py, renku/ui/cli/workflow.py, renku/ui/service/controllers/workflow_plans_export.py, renku/ui/service/serializers/workflows.py, renku/ui/service/views/api_versions.py, renku/ui/service/views/workflow_plans.py, tests/core/plugins/test_workflow.py, tests/fixtures/runners.py, tests/service/views/test_workflow_plan_views.py, tests/utils.py
closes #3190 
Adds a workflow export endpoint.
I had to also re-format a big part of the cwl export methods to:
- not use absolute paths
- not use multiple workflow files (but just one with embedded workflows)
=> feat(service): add workflow export endpoint

renku/core/dataset/dataset.py, renku/ui/cli/dataset.py
=> fix(cli): prevent pre-commit hook error for non-dataset files

helm-chart/renku-core/values.yaml, poetry.lock, pyproject.toml
=> chore: remove v8 from core-service

renku/core/template/template.py, renku/domain_model/template.py, renku/ui/service/controllers/templates_create_project.py, tests/fixtures/templates.py, tests/service/controllers/test_templates_create_project.py, tests/service/views/test_templates_views.py, tests/utils.py
=> fix(service): use temporary directory to clone project templates on project creation

poetry.lock, pyproject.toml
different solution from the one for 2.x since we use different poetry versions
=> fix(cli): fix toil dependency being treated as optional

renku/ui/cli/run.py, tests/cli/test_workflow_file.py
=> fix(workflow): better error message when running non-existing workflow file

.github/workflows/test_deploy.yml, poetry.lock, renku/core/constant.py, renku/core/dataset/providers/api.py, renku/core/errors.py, renku/core/session/docker.py, renku/core/session/renkulab.py, renku/core/session/session.py, renku/core/util/jwt.py, renku/domain_model/session.py, renku/ui/cli/init.py, renku/ui/cli/session.py, renku/version.py, tests/cli/test_init.py, tests/cli/test_migrate.py, tests/cli/test_session.py, tests/cli/test_template.py, tests/core/commands/test_merge.py, tests/core/plugins/test_session.py, tests/fixtures/repository.py, tests/fixtures/session.py, tests/fixtures/templates.py, tests/service/fixtures/service_integration.py
Various `renku session` fixes. Removes anonymous sessions.
Fixes #3253 
Fixes #2961 
Fixes #3267 
Fixes #3291 
Fixes #3295 
Fixes #3298 (only the bug report part)
=> fix(cli): various renku session fixes

.github/workflows/test_deploy.yml, renku/ui/cli/init.py, tests/cli/test_init.py, tests/cli/test_migrate.py, tests/cli/test_template.py, tests/core/commands/test_merge.py, tests/fixtures/repository.py, tests/fixtures/templates.py, tests/service/fixtures/service_integration.py
Comment to satisfy checkdeploy
=> chore: revert templates id changes

renku/ui/cli/service.py, renku/ui/service/cache/base.py, renku/ui/service/cache/config.py
=> fix(svc): properly use Redis sentinel

renku/command/checks/__init__.py, renku/command/checks/activities.py, renku/command/checks/workflow.py, renku/core/migration/m_0009__new_metadata_storage.py, renku/core/migration/m_0010__metadata_fixes.py, renku/core/util/datetime8601.py, renku/core/util/git.py, renku/data/shacl_shape.json, renku/domain_model/workflow/plan.py, renku/infrastructure/gateway/database_gateway.py, renku/ui/service/serializers/templates.py, tests/core/metadata/test_project_gateway.py, tests/core/models/test_activity.py, tests/core/test_plan.py, tests/utils.py
Fixes some v10 migration issues.
=> fix(core): metadata v10 migration fixes

renku/infrastructure/repository.py
Fixes incompatibility with python 3.7 that was causing tests to fail
=> test: fix code for tests with python 3.7

renku/core/dataset/dataset.py, renku/core/dataset/dataset_add.py, renku/core/util/git.py, renku/domain_model/dataset.py
closes #3332 
I tested it with the mscoco dataset the user mentioned and it took 55 seconds to add.
=> fix: parallelize dataset add for performance

renku/ui/cli/service.py, renku/ui/service/cache/base.py, renku/ui/service/cache/config.py
Backport redis sentinel changes to also work on old service
=> fix(svc): properly use Redis sentinel (#3319)

renku/core/session/docker.py, tests/cli/test_session.py
=> fix(cli): fix starting local session as user without uid 1000

renku/ui/service/controllers/templates_create_project.py, renku/ui/service/errors.py
=> fix(service): fix error message for invalid templates

renku/core/session/docker.py
=> feat(cli): allow setting local port on session docker provider

.github/workflows/pypi-release.yml, .github/workflows/release.yml, .github/workflows/test_deploy.yml
=> chore: change CI to create pre-releases

.github/workflows/test_deploy.yml, DEVELOPING.rst
Fixes bug with proper versions when no release candidate exists yet
=> chore: fix pypi release action

renku/command/format/session.py, renku/core/session/docker.py, renku/core/session/renkulab.py, renku/domain_model/session.py, renku/ui/cli/session.py, tests/cli/test_session.py, tests/fixtures/session.py
=> feat(cli): pretty session list output with additional fields

renku/core/storage.py, renku/core/workflow/model/workflow_file.py, tests/core/workflow/test_workflow_file.py
=> fix(core): fix trying to pull external files from LFS, prohibit external files in workflows

.github/workflows/combine-dependabot-updates.yml
the used action was deleted and dependabot just breaks if it can't find an action.
=> chore: fix dependabot updates

helm-chart/renku-core/templates/deployment.yaml, renku/command/command_builder/database.py, renku/ui/service/controllers/templates_create_project.py, renku/version.py, tests/service/controllers/test_templates_create_project.py
=> feat(service): allow setting default CLI version for project creation

.github/workflows/combine-dependabot-updates.yml
all the official actions don't properly deal with poetry.lock merge conflicts, defeating the purpose of having an action for this.
=> chore: fix combined PR action to work with poetry lock

renku/command/schema/agent.py, renku/core/dataset/providers/dataverse.py, renku/core/dataset/providers/dataverse_metadata_templates.py, renku/core/dataset/providers/zenodo.py, renku/core/migration/models/v9.py, renku/domain_model/dataset.py, tests/cli/test_integration_datasets.py
Includes dataset keywords when exporting a dataset to external data warehouses.
Fixes #1212
=> feat(dataset): export dataset keywords

renku/ui/service/errors.py
This will show a valuable reference to the documentation when the error is triggered.
=> chore: add documentation reference to UpdateProject error

.github/workflows/test_deploy.yml
since we don't run the service on macos
=> chore: remove service tests for macos in CI

renku/core/workflow/run.py
=> fix(cli): don't swallow command output in renku run

renku/core/migration/migrate.py
/deploy #persist extra-values=global.renku.cli_version=2.5.0rc2
=> fix(service): do not suggest updating dockerfile for release candidate versions

docs/reference/commands/index.rst
Needed by https://github.com/SwissDataScienceCenter/renku/pull/3063
=> docs: add reference to be used from the main docs

renku/core/dataset/providers/renku.py
=> fix(cli): adapt to changes in KG api for importing datasets

renku/core/workflow/plan_factory.py, renku/core/workflow/run.py, renku/domain_model/workflow/parameter.py, renku/ui/cli/run.py, tests/api/test_parameter.py, tests/cli/test_output_option.py
=> feat(cli): allow disabling automated parameter detection in renku run

CHANGES.rst, poetry.lock, pyproject.toml, renku/ui/service/cache/config.py, renku/ui/service/controllers/api/mixins.py, renku/ui/service/controllers/templates_create_project.py
fixes issues with core-service redis not being properly isolated and not properly checking if a project is in cache.
=> chore: release v1.11.4

renku/core/session/session.py
=> fix(cli): parse security_opt as list not tuple

renku/command/checks/__init__.py, renku/command/checks/workflow.py, renku/ui/service/serializers/workflows.py, tests/core/test_plan.py
=> fix(cli): correct bad plan ID format

renku/ui/service/serializers/version.py
=> fix(service): return project version as int

renku/ui/service/controllers/cache_migrations_check.py, renku/ui/service/serializers/cache.py
=> fix(service): remove doctor check from cache.migrations_check

renku/domain_model/dataset.py
=> fix(core): properly formatted dataset image IDs

CHANGES.rst
Updating the changelog for the release in hotfix/2.6.1 branch
=> chore: update changelog for 2.6.2 bugfix release

.github/workflows/acceptance-tests.yml
=> chore: add data svc to deploy action

pyproject.toml, renku/__init__.py
=> fix: prevent distutils warning

renku/ui/service/controllers/datasets_edit.py
=> fix(service): allow editing datasets without creator email

renku/domain_model/dataset.py, tests/service/views/test_dataset_views.py
=> feat(service): date_published in datasets.list response

renku/core/migration/migrate.py, renku/ui/service/controllers/cache_migrate_project.py
=> fix(svc): fix migration not working with old template metadata

renku/ui/service/serializers/version.py, tests/service/views/test_version_views.py
=> fix(service): properly return cli_version in api version

renku/infrastructure/gateway/activity_gateway.py
=> fix: properly remove activities in workflow remove if catalog is corrupt
