docs/cli.rst, docs/client.rst, docs/index.rst, renga/api/storage.py, renga/cli/__init__.py, renga/cli/_client.py, renga/cli/_config.py, renga/cli/_options.py, renga/cli/add.py, renga/cli/init.py, renga/cli/io.py, renga/cli/login.py, renga/models/_datastructures.py, renga/models/deployer.py, renga/models/projects.py, renga/models/storage.py, renga/notebook.py, tests/conftest.py, tests/test_cli.py, tests/test_client.py
=> docs & cli: improvements

.editorconfig, Makefile
tag by default so that proper tags are made when used with the makefile from the renga repo
addresses https://github.com/SwissDataScienceCenter/renga/issues/121
=> makefile: make tags by default

renga/cli/_git.py, renga/cli/_repo.py, renga/cli/datasets.py, renga/cli/init.py, renga/cli/run.py, renga/models/cwl/command_line_tool.py, tests/test_cli.py
- initialize LFS on project init
- track CWL tool outputs in LFS
waiting on #115 before adding the integration for datasets
---
addresses #104
=> LFS support for renga run

renga/cli/_ascii.py, renga/cli/_graph.py, renga/cli/status.py
=> graph: resolve lineage in submodules

renga/cli/_graph.py, renga/models/cwl/parameter.py, renga/models/cwl/process.py, renga/models/cwl/workflow.py
=> cwl: fix workflow serialization

Makefile
use `--password-stdin` to avoid questions from docker
=> dockerhub: use --password-stdin for login

setup.py
Currently the runner fails when trying to build the dot files for the graph due to a missing library (pydot). Couldn't test if this actually fixes it, but it's my best guess...
=> setup: add pydot dependency to fix gitlab runner

renku/cli/update.py, renku/version.py
Solves problem with `click` running on Python 3 discovered by @mitch-volpi
=> cli: preserve environment variables during update

renku/cli/_cwl.py
* Fixes problem on Linux when the outputs are stored on a different
filesystem than the repository. (closes #231)
=> cli: use shutil.move instead of os.rename

renku/cli/.gitlab-ci.yml
reduces the build time to just a few seconds on trivial image builds
closes https://github.com/SwissDataScienceCenter/renku/issues/326
=> gitlab-ci: use docker:stable for image build

renku/models/cwl/command_line_tool.py, renku/models/cwl/process_requirements.py, tests/test_cwl.py
Makes sure that only the defined output directory is listed in tool outputs and not the files it contains.
The pre-existing output directory MUST be empty before running the command.
(closes #309)
=> cwl: support pre-existing output directory

renku/api/datasets.py, renku/cli/dataset.py, renku/models/datasets.py, tests/test_cli.py, tests/test_dataset.py
This PR addresses two problems:
* using `--relative-to` was resulting in unexpected directory trees since it also injected the name of the parent project -- this is now removed
* it adds support for importing via `git+ssh` e.g. `renku dataset add mydata git+ssh://myhost.io/namespace/project.git`
addresses #214 
=> Improve import

renku/cli/_format.py, renku/cli/log.py
Provides an option for a simplified dot graph generation showing only inputs, outputs, and processes.
Fixes #339 
- New feature (non-breaking change which adds functionality)
=> Make dot output simpler by default

setup.py
build failing due to a compatibility issue with `cwltool` -- pins the tool to the current minimum required version until this problem is resolved. 
closes #348
=> pin cwltool version

.dockerignore, Dockerfile
Fixes Docker builds since Git repo is required to correctly detect the package version.
=> docker: build from git

renku/models/_git.py, tests/models/test_git.py
closes #371 
- Bug fix (non-breaking change which fixes an issue)
- I have added tests to cover my changes.
- I have run ``./run-tests.sh`` locally.
=> models: allow for '.' and '-' in repo path

.travis.yml, Pipfile.lock, setup.py
Fixes CVE-2017-18342 by old version of `pyyaml`.
=> pipenv: fix CVE-2017-18342

renku/cli/update.py, tests/cli/test_update.py, tests/test_cli.py
Separates cli tests and adds support for updating output directories.
Fixes #387
--
cc @LiliGasser
=> cli: allow update of directories

renku/api/_git.py, renku/cli/_cwl.py, renku/cli/run.py, renku/models/cwl/command_line_tool.py, setup.py, tests/cli/test_output_option.py
Automatically removes specified outputs before executing a `renku run` command.
Addresses #387 
=> cli: remove outputs before run

setup.py
The latest release of `pytest-flake8==1.0.4` removes the incompatibility with `flake8==3.7`.
=> installation: unpin flake8

renku/models/provenance/activities.py, renku/models/provenance/entities.py
Exports missing triples and adds `path` as `schema.org/name` for `Entities`.
Addresses #370
=> models: export path and parent directories

renku/cli/init.py, tests/cli/test_init.py
Handles case when when running `renku init --force` fails badly on empty directory.
(closes #404)
=> cli: init --force on empty dir

renku/api/_git.py, renku/api/storage.py
Prevents creation of duplicates in `.gitattributes` when a general rules exists.
(closes #410)
cc @lusamino
=> api: get git attrs for files to prevent duplicates

renku/api/datasets.py, renku/cli/__init__.py, renku/cli/_checks/__init__.py, renku/cli/_checks/location_datasets.py, renku/cli/doctor.py, renku/cli/migrate.py, renku/models/datasets.py, renku/models/refs.py, tests/test_cli.py, tests/test_dataset.py
Moves location of dataset metadata file from `data/<name>/metadata.yml`  to `.renku/datasets/<name>/metadata.yml`
(closes #396)
=> api: move metadata to .renku/datasets

Pipfile.lock, renku/cli/dataset.py, renku/models/datasets.py, tests/test_cli.py
This PR adds a feature for ```renku datasets``` command to list all created datasets within a repo.
Implements #417 
Example output which should be produced:
```
SHORT_ID    NAME         AUTHORS_CSV    CREATED
----------  -----------  -------------  -------------------
87c46dd9    somedataset  sam            2019-02-18 13:47:10
5aa65a26    dataset1234  sam            2019-02-18 13:47:39
```
=> feat(datasets): added listing of datasets

CHANGES.rst, README.rst
*(released 2019-03-05)*
- Adds ``renku mv`` command which updates dataset metadata, ``.gitattributes``
and symlinks.
- Pulls LFS objects from submodules correctly.
- Adds listing of datasets.
- Adds reduced dot format for ``renku log``.
- Adds ``doctor`` command to check missing files in datasets.
- Moves dataset metadata to ``.renku/datasets`` and adds ``migrate datasets``
command and uses UUID for metadata path.
- Gets git attrs for files to prevent duplicates in ``.gitattributes``.
- Fixes ``renku show outputs`` for directories.
- Runs Git LFS checkout in a worktrees and lazily pulls necessary LFS files
before running commands.
- Asks user before overriding an existing file using ``renku init``
or ``renku runner template``.
- Fixes ``renku init --force`` in an empty dir.
- Renames …
=> release: v0.4.0

renku/api/datasets.py, renku/cli/dataset.py, tests/cli/test_datasets.py
This PR removes --copy/--no-copy flags on add command and introduces --link flag which will create a hardlink of the file into dataset.
Fixes #448
=> fix(datasets): link flag on dataset add

renku/api/datasets.py, renku/api/repository.py, renku/cli/_format/graph.py, renku/models/_jsonld.py, renku/models/_locals.py, renku/models/cwl/_ascwl.py, renku/models/cwl/command_line_tool.py, renku/models/cwl/parameter.py, renku/models/cwl/types.py, renku/models/provenance/activities.py
=> feat(models): reference context for relative paths

renku/api/datasets.py, renku/api/repository.py, renku/cli/_client.py, renku/cli/init.py, renku/cli/migrate.py, renku/cli/run.py
* Moves locking to CLI from API.
=> fix(api): make methods lock free

CHANGES.rst
* **api:** make methods lock free ([1f63964](https://github.com/jirikuncar/renku-python/commit/1f63964)), closes [#486](https://github.com/jirikuncar/renku-python/issues/486)
* use safe_load for parsing yaml ([5383d1e](https://github.com/jirikuncar/renku-python/commit/5383d1e)), closes [#464](https://github.com/jirikuncar/renku-python/issues/464)
* **datasets:** link flag on dataset add ([eae30f4](https://github.com/jirikuncar/renku-python/commit/eae30f4))
* **api:** list datasets from a commit ([04a9fe9](https://github.com/jirikuncar/renku-python/commit/04a9fe9))
* **cli:** add dataset rm command ([a70c7ce](https://github.com/jirikuncar/renku-python/commit/a70c7ce))
* **cli:** add rm command ([cf0f502](https://github.com/jirikuncar/renku-python/commit/cf0f502))
* **cli:** configurable …
=> build(release): v0.5.0

docs/index.rst
The CLI is not using any specific Renku API for now.
=> docs: remove outdated link

conftest.py, renku/api/datasets.py, tests/cli/test_datasets.py
When adding data to a dataset from a URL which includes a query string, this query string used to be present in the filename. This is now fixed.
Closes #544
=> fix(datasets): strip query string from data filenames

renku/api/storage.py, tests/test_cli.py
Checking for LFS usage in Renku project was looking into current repo git config file and all the higher level files (i.e. user and system). If LFS filter was enabled in any of these config file, Renku would try to use it even if it was told not to when initialising the project.
This fix only looks in repository's git config.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/562.
=> fix: only check local repo for lfs filter

.travis.yml
Change the travis-ci setup to skip integration tests on PRs. They will run once the PR is merged and on cron jobs.
=> build(ci): skip integration tests on prs

renku/api/_git.py, renku/models/provenance/activities.py, renku/models/provenance/agents.py, setup.py
This PR links every activity to the version of `renku` used to generate the triples. This way we can check in the future which parts of the graph may need to be regenerated. 
---
closes #508
=> feat: add SoftwareAgent to Activity

.travis.yml, CHANGES.rst
This PR:
* removes the docker build (not needed anymore since the KG is hosted and dot files are not generated in CI)
* push dev tags to have consistency between pypi releases and repo tags
* updates changelog
=> build: update and cleanup build

.travis.yml
mac os x build regex was missing a `v`.
=> build: use correct tag regex

renku/api/datasets.py, renku/cli/_format/graph.py, renku/models/datasets.py, renku/models/provenance/agents.py, tests/cli/test_datasets.py
Sets the `client` property of files in a dataset after the dataset has been loaded. This is needed to ensure the `full_path` property of files returns the correct path to a file irrespective of the current working directory.
Also adds a new unit test to check for this case
Fixes #617
=> Fix zenodo export relative path

renku/cli/_providers/zenodo.py
Adds a small hint about `renku dataset edit` to the Zenodo export command error message if metadata is missing. 
Not a huge improvement but since metadata will be overhauled anyways it should at least help (power-)users to figure things out until that is done.
Fixes #618 
=> FIX: Add better error message when metadata is missing in zenodo export

README.rst
Fixes a wrong flag in the docs related to installing dev versions of renku via pip
=> Fixes pip install flag for installing pre-releases

renku/models/datasets.py, renku/models/provenance/activities.py
This PR:
* prevents the creation of nodes with `mailto:None` ids - instead, if we don't have obvious identifying information like an email or an orcid-id we simply generate a blank node
* adds the `Person` `prov:agent` to the commit activity - this is the human agent that created the commit
This is a sample graph:
Fixes #634 
Fixes #632
=> add human commiter to KG and clean up dataset creator ids

renku/models/datasets.py
Adds `name` attribute that maps to `schema:name` for `DatasetFile`. 
closes #640
example graph:
=> feat: export filename as schema:name

renku/api/datasets.py, renku/models/_jsonld.py, renku/models/datasets.py, renku/models/provenance/entities.py, tests/test_dataset.py
Always add a `commit` to `Dataset` if possible - in the case where a dataset is first being created with `with_dataset`, it won't have been committed yet.
This addresses #646 but needs the resolution of #639 for a full solution.
=> fix: always add commit to dataset if possible

renku/cli/run.py, renku/models/cwl/command_line_tool.py, tests/cli/test_indirect.py
Renku can read additional lists of inputs and inputs from files. When execution of a script finishes and before any further processing, Renku looks for existence of `.renku/tmp/inputs.txt` and `.renku/tmp/outputs.txt`. Each line in these files correspond to a filename in the Renku project directory. Renku marks all these filenames as explicit inputs and outputs and deletes those two files. It then resumes the rest of the processing.  
Renku delete the `inputs.txt` and `outputs.txt` files before running the script.
The location of these two files within the Renku project directory can be controlled by setting `RENKU_FILELIST_PATH` environment variable. If set, it points to the directory within the project directory which `inputs.txt` and `outputs.txt` reside.
Fixes …
=> feat: support for indirect inputs and outputs

renku/cli/_providers/zenodo.py
There is no validation on the metadata uploaded to Zenodo before hand. Users get error about missing metadata when they uploaded their possible huge data. This PR uploads the metadata first and then uploads the actual files. User would see error before spending much time. I've tested this on Zenodo with a dummy dataset and all files where uploaded along with the metadata.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/625
=> fix: upload metadata before actual files

renku/api/datasets.py, renku/cli/dataset.py, renku/models/datasets.py, tests/test_dataset.py
closes: #628 
This fixes the bug mentioned in #628 though it does not make DatasetFile properties lazy loading, as that was not the cause of this problem.
When importing a `DatasetFile` via the `renku import` command, the `add_to_dataset` method in `renku/cli/dataset.py` first calls `client.add_data_to_dataset(...)` to add (and commit the files, but then calls `dataset.update_metadata(with_metadata)` to update the metadata. But since `files` are considered metadata by `update_metadata(...)`, the original, uncommitted file entries overwrite the newly created entries.
As this will be reworked soon with the big CLI changes, this is just a quick&dirty hotfix that copies over the labels/commits of the files before they get overwritten (as discussed with @jsam ). …
=> fix: adds _label and commit data to imported dataset files, single commit for imports

conftest.py, tests/test_cli.py
Runs test with a temporary config directory
=> fix: renku config overwrite when running tests

renku/models/provenance/activities.py
`commit` was not getting set when loading a `Dataset` node in the graph, resulting in an exception when `renku log`ing to ascii.
=> bug: Fixes missing commit on generation object for Dataset entities

renku/cli/dataset.py, tests/cli/test_datasets.py
Closes #642 
click prompts in dataset cli command were missing `abort=True`, leading to empty commits being created.
=> bug: Adds missing abort to click prompts

renku/models/provenance/entities.py
@vfried and @jachro reported a problem that datasets were not showing up in queries for forked projects. This PR forces the project to be set to the current project even if this is not what is recorded in the metadata. This might seem strange, but:
- the information that the dataset/file is already a part of the parent project is already recorded in the KG
- the use is unlikely to scrutinize or use this part of the dataset metadata since it is internal to renku
=> fix: force current project for entities

.travis.yml, renku/cli/dataset.py, renku/core/commands/client.py, renku/core/commands/dataset.py
Closes #718 
Replaced code with a decorated wrapper function and the actual functionality so a client can be manually passed to the function if necessary.
=> fix: dataset import causes renku exception due to duplicate LocalClient

renku/core/management/repository.py, renku/core/models/datasets.py, renku/core/models/jsonld.py, renku/core/models/projects.py, tests/core/commands/test_dataset.py, tests/core/commands/test_projects.py
The PR corrects the wrong behavior that the user executing the git command was being set as the project creator. Instead, if the project creator does not exist, the git history of `.renku/metadata.yml` is searched for the first commit and its author is used as the project creator. 
closes #713
=> fix: use commit author for project creator

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/compat.py
Removes the click dependencies from `import` and `export` commands by using callbacks and partial context managers.
Still ugly, see #737 to add a sane communication pattern between cli and core. Left as is since it blocks other work and it's good enough for now.
Closes #702
=> Remove click dependencies from import and export commands

renku/core/commands/dataset.py
Fixes a regression remained from refactoring Renku python which prevents importing of Zenodo datasets.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/743
=> fix: zenodo dataset import error

renku/cli/dataset.py, renku/core/commands/checks/migration.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, renku/core/management/repository.py, renku/core/models/datasets.py, tests/cli/test_datasets.py, tests/cli/test_move.py, tests/core/commands/test_cli.py, tests/core/commands/test_dataset.py
This PR removes the need to use submodules for importing datasets from Git repos in Renku. It stores the source of each file added to a dataset by using a `schema:isBasedOn` (https://schema.org/isBasedOnUrl) field to point to the remote file.
It also changes the command line interface: The `--target` and `--relative-to` options are removed from `dataset add` commands. Now, one can use `--source` and `--destination` options to say which files are copied from a remote repo and to which location.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/681
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/670
closes #214 
**Do not create pull …
=> 681 add to dataset without submodules

renku/core/errors.py, renku/core/management/datasets.py, tests/cli/test_datasets.py
When creating a dataset (either directly or via add command) fails, we cannot repeat the command by some weird error message. This is because symbolic references to dataset metadata is created and not removed upon an error. This PR fixes this issue by cleaning up after a failure.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/684
=> fix: clean up dataset references when create or add fails

MANIFEST.in, conftest.py, renku/core/commands/checks/migration.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, renku/core/management/repository.py, renku/core/models/datasets.py, renku/core/models/migrations/__init__.py, renku/core/models/migrations/dataset.py, renku/core/models/provenance/activities.py, renku/core/models/refs.py, renku/core/utils/datetime8601.py, tests/cli/test_migrate.py, tests/core/commands/test_serialization.py, tests/fixtures/doi-dataset.yml
This PR tries to solve the problem of poorly-formed dataset `id`s. Specifically: 
* when a doi is available, use it as the identifier; we use just the doi itself e.g. `10.5281/zenodo.3251128` and not the full URI e.g. `https://doi.org/10.5281/zenodo.3251128`
* the id is always a URI that uses the `identifier`; if the `identifier` is a doi, it is URL-escaped
* older metadata (`id=doi` and `identifier=uuid`) is automatically migrated
* adds a `sameAs` triple pointing to the original doi
Example:
```json
{
"@context": "http://schema.org",
"id": "https://dev.renku.ch/datasets/10.5281%2Fzenodo.3247009",
"type": [
"http://www.w3.org/ns/prov#Entity",
"Dataset",
"http://purl.org/wf4ever/wfprov#Artifact"
],
"creator": {
"id": "https://orcid.org/0000-0002-3730-5348",
"type": "Person",
"name": …
```
=> feat: use URIs for dataset ids

renku/core/management/repository.py, renku/core/models/projects.py, tests/core/models/test_projects.py
closes #554
also, updates the `id` of the serialized project if a remote exists and the previous `id` contains `file://`. 
The resulting json-ld looks like:
```
{
"@context": {
"schema": "http://schema.org/",
"prov": "http://www.w3.org/ns/prov#"
},
"@id": "https://renkulab.io/projects/rok.roskar/test-init",
"@type": [
"prov:Location",
"schema:Project"
],
"schema:creator": {
"@id": "mailto:rok.roskar@sdsc.ethz.ch",
"@type": "schema:Person",
"schema:email": "rok.roskar@sdsc.ethz.ch",
"schema:name": "Rok Roskar"
},
"schema:dateCreated": "2019-09-20T11:30:38.639529+00:00",
"schema:dateUpdated": "2019-09-20T11:30:38.641184+00:00",
"schema:name": "test-init",
"schema:schemaVersion": "2"
}
```
=> feat: use UI-resolved project path as project ID

.github/workflows/test.yml
Github renamed `version` to `python-version`
=> fix: Updates github actions to new syntax

renku/core/management/datasets.py, tests/cli/test_datasets.py
In previous Renku version, we could create nested datasets (e.g. `new/2018`, `new/2019`). In recent, Renku versions this is not possible, however, the error message printed to the user is not useful. This PR prints a useful error message to users.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/789
=> feat: avoid creation of nested datasets

renku/core/models/jsonld.py
Bugfix for issue in #753 where a type of `mls:...` gets interpreted as a list of characters instead, leading to invalid types.
=> fix: fixes nested type scoped context handling for single types

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, tests/cli/test_integration_datasets.py
When adding a file from a Git repository to a dataset, this PR makes it possible to add a specific version of the file by passing a `--ref` option. It can point to a branch, commit, or tag. Similarly, it allows to update a dataset to a specific version.
Moreover, this PR fixes two issues with Git-LFS: 1. Dataset files now are tracked in the LFS, and 2. When cloning a repo only desired files are pulled from LFS.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/802
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/803
=> Add or update a specific commit; LFS fixes

conftest.py, renku/cli/dataset.py, renku/cli/exception_handler.py, renku/core/commands/dataset.py, renku/core/errors.py, renku/core/management/datasets.py, tests/cli/test_datasets.py, tests/core/commands/test_cli.py, tests/core/commands/test_dataset.py
This PR enables copying metadata from other Renku projects when adding files to datasets. ATM, only `creator` is copied over from the original dataset's metadata.
Moreover, if fixes some minor issues with `renku dataset add` and `renku dataset update`.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/99
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/763
=> 99 import dataset from renku aware repo

conftest.py, renku/core/commands/checks/migration.py, renku/core/models/datasets.py, renku/core/utils/urls.py, tests/cli/test_migrate.py, tests/core/commands/test_serialization.py, tests/fixtures/broken-dataset-v0.5.2.yml
=> fix: adds simple check on empty filename

docs/models/datasets.rst, renku/cli/exception_handler.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, renku/core/management/repository.py, renku/core/models/datasets.py, renku/core/models/projects.py, renku/core/models/provenance/agents.py, tests/core/commands/test_dataset.py, tests/core/commands/test_serialization.py, tests/core/models/test_projects.py
This change removes `Creator` in favor of having a single `Person` type. Fixes (and adds a test for) the regression described in #812. 
*NOTE*: This PR is against the `0.7.0-maint` branch - when merged, we will tag a patch release `0.7.2`.
=> fix: ensure person ids are valid

renku/core/management/git.py
Creating a commit in a renku project may result in a wrong commit date depending on the specific timezone and period of the year.
This change removes the possibility to set a custom date during the commit (it was implemented but never used), allowing the `GitPython` library to fall back to the effective current time.
To test this PR, invoke `renku init` command and check the commit date though `git log`. The error is easily reproducible with local timezone set to `CET`
=> fix: remove custom date from commit

renku/core/commands/dataset.py, renku/core/management/datasets.py, tests/cli/test_datasets.py
When adding the same file to a dataset, nothing changes but two empty commits are created. This PR fails with an error message in this case and avoids creating empty commits.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/795
=> fix: avoid empty commits when adding files

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, renku/core/management/git.py, renku/core/utils/urls.py, tests/cli/test_datasets.py
Remove username and passwords from URLs from dataset metadata and commit message when adding data to a dataset. It also removes local paths from metadata when adding a file from local filesystem.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/476
=> feat: do not store url credentials anywhere

.github/workflows/semantic_pr.yml
Adds a github action to enforce that PR titles conform to conventional commits syntax
=> chore: Adds semantic PR github action

renku/core/commands/checks/githooks.py, renku/data/pre-commit.sh, tests/core/commands/test_doctor.py
`renku doctor` command also checks for the existence of the git hooks and checks that their content is up-to-date.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/479
=> feat: check for required git hooks

.github/workflows/semantic_pr.yml, renku/core/commands/client.py, renku/core/commands/clone.py, renku/core/commands/config.py, renku/core/commands/dataset.py, renku/core/commands/migrate.py, renku/core/errors.py, renku/core/management/git.py, tests/core/commands/test_dataset.py
=> feat: add optional commit message

renku/core/management/clone.py, tests/cli/test_integration_datasets.py
If we don't provide a path when running renku clone URL, Renku by default uses the current directory to clone the repo which can fail if current directory is not empty. This PR uses project's name as the default target path which is in par with what Git does.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/856
=> feat: use project name as default path when cloning

renku/cli/dataset.py, renku/core/commands/checks/migration.py, renku/core/commands/dataset.py, renku/core/commands/format/datasets.py, renku/core/errors.py, renku/core/management/datasets.py, renku/core/models/datasets.py, renku/core/models/provenance/activities.py, renku/core/models/provenance/agents.py, renku/core/models/refs.py, renku/data/shacl_shape.json, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py, tests/core/commands/test_serialization.py
When creating datasets, users can provide its description, creators, and display name using command line options. Creator is a string with "Name <email>" format and users can pass multiple creators. 
This also makes a consistent use of `short_name` in the code. `short_name` is used as the dataset's data directory name and dataset's reference name. `name` is not used by Renku other than storing it as a metadata. If users don't provide a short name when creating a dataset then one is automatically created.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/515
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/791
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/840
=> feat: metadata on dataset creation

.github/workflows/integration_tests.yml, .github/workflows/test.yml, Pipfile, Pipfile.lock, renku/cli/__init__.py, renku/core/commands/checks/__init__.py, renku/core/commands/format/graph.py, renku/core/compat.py, setup.py
This PR aims to make renku compatible with python 3.8.
There is an issue with `cgi.escape()` that has been removed in favour of `html.escape()` https://docs.python.org/3.7/library/cgi.html#cgi.escape
I changed that in our codebase but it turns out it's used also in some other libraries that are sub-dependencies. This makes a test fail (specifically for `renku log --format dot-debug`). The second commit simply removes that from the format list -- I guess this workaround is not good since that format was introduced a few months ago
=> feat: python 3.8 compatibility

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/models/provenance/agents.py, renku/service/serializers/datasets.py, renku/service/views/datasets.py, tests/cli/test_datasets.py
closes: #874 
* improves the interface of dataset create for the service needs
* addresses a problems raised by linter
* adds ability to set metadata from the service
=> fix: service dataset.create with additional metadata

renku/core/commands/format/datasets.py, renku/core/models/datasets.py
* Re-aranges dataset list tabular display to better fit the screen
* Adds a tags to display tabular format
master:
```
ID                                    SHORT_NAME                        VERSION    CREATED              CREATORS
------------------------------------  --------------------------------  ---------  -------------------  ----------
0c829efa-8f54-4dd6-a143-d09a02c77ea0  7b68e6c5afba4e1f90afa59c495d337b             2019-12-03 08:09:03  J.Sam
22147c19-08e7-40c1-9311-79f0b184cb5e  5f480578f60b40f9845015f4c184f965             2019-12-04 17:39:37  J.Sam
```
This PR changes master preview to the following:
```
> renku dataset
ID                                    CREATED              SHORT_NAME                CREATORS    TAGS    VERSION
------------------------------------ …
```
=> chore: updated format of tabular datasets list

renku/core/management/git.py
Changes `git worktree prune` to the new `git worktree remove` command that also deletes the temporary directory and removes the temporary branch if one was created.
Closes #686
=> fix: Deletes temporary branch after renku init --force

renku/cli/run.py
Adds documentation to clear up misunderstanding regarding circular dependencies.
Closes #656
=> docs: Adds documentation about circular dependencies in renku run

Dockerfile.svc
Extends gunicorn default timeout to enable long-running file uploads.
=> fix: extended gunicorn worker timeout

.github/workflows/test_deploy.yml
runs 3.7 macos integration on prs and 3.6, 3.7, 3.8 integrations on master/tags
=> chore: Only execute all macos integration tests on master/tags

Pipfile.lock
Concourse keeps failing because of the `Pipfile.lock` being outdated. This PR should fix the problem.
=> chore: update Pipfile.lock to match latest Pipfile

renku/core/commands/providers/zenodo.py, tests/cli/test_integration_datasets.py
This PR fixes serialization of zenodo metadata for cases when there is extra metadata to consume. In case of extra metadata, serialization will put this extra metadata to extras key instead of raising exception.
closes: #937 
closes: #885
=> fix: serialize all zenodo metadata

renku/core/errors.py, renku/core/management/datasets.py, renku/core/management/repository.py, tests/cli/test_datasets.py
Adds `.git/, .renku/, Dockerfile, environment.yml, .dockerignore, .gitignore, .gitlab-ci.yml, requirements.txt` as protected files that can't be added to a dataset. Adding to a dataset will store the file on LFS and the gitlab runner doesn't have LFS access, so I added more paths than the original issue asked for.
Closes #873
=> feat: Adds protection for renku relevant paths in dataset add

renku/core/management/storage.py
LFS does not work with absolute paths, for whatever reason.  So with cwd = `/work/flights-tutorial-data/`.
`git lfs pull -I /work/flights-tutorial-data/data/201901_us_flights_1/2019-01-flights.csv.zip` does not download the file from lfs, but `git lfs pull -I data/201901_us_flights_1/2019-01-flights.csv.zip` does.
I couldn't find any info on this on the net, but this PR fixes it.
Closes #903
=> fix: changes lfs pull paths to be relative to parent

.gitignore
IdeaJ added support for file based project files (instead of .idea) for Python. This PR adds those  and `iws` files to `.gitignore`.
=> fix: ignore file based project files

.github/pr_labels.yml, .github/workflows/pipfile-update.yml, .github/workflows/test_deploy.yml, .mergify.yml
Instead of the default `GITHUB_TOKEN` use the bot-user token to ensure that the automated Pipfile commits trigger a new build. 
This includes and will close #958
=> chore: use bot CI token for Pipfile updates

renku/core/management/storage.py, tests/cli/test_datasets.py
Resolves symlinks before pulling data from LFS.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/462
=> fix: resolve symlinks when pulling LFS

renku/cli/show.py, renku/core/commands/graph.py
Fixes some bugs with the `renku show siblings` command and changes the output so it's grouped by sibling-hood, for instance:
```
$ renku show siblings
figs/cumulative.png
figs/grid_plot.png
---
data/.gitkeep
---
f2
f1
```
Groups of siblings are separated by `---`, so it's easy to spot which paths belong together.
Also adds a `--flat` flag that produces a flat list with no duplicates, as well as a `--verbose` flag that also outputs commit information:
```
$ renku show siblings f1 f2
f2
f1
---
f2
f3
$ renku show siblings -f f1 f2
f1
f3
f2
$ renku show siblings -f -v f1 f2
f2 @ 5822f230ded10d296ffc48d362e6e92a9a5df585
f2 @ 433c96eeebf545bff7badb916bee8d195fd1477b
f1 @ 433c96eeebf545bff7badb916bee8d195fd1477b
f3 @ 5822f230ded10d296ffc48d362e6e92a9a5df585
$ renku show siblings -v f1 f2
f2 @ …
```
=> fix: Fixes renku show sibling handling with no paths

.github/workflows/test_deploy.yml, .github/workflows/test_publish.yml, conftest.py, renku/core/utils/contexts.py, run-tests.sh, setup.cfg, tests/cli/test_integration_datasets.py
Deletes unpublished Dataverse datasets when integration tests are done. For testing published datasets, it creates a GH action that runs this tests on merges to master when one of the files in `renku/core/commands/providers` change.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1035
=> fix: Dataverse integration tests

renku/cli/dataset.py, renku/cli/remove.py, renku/cli/rerun.py, renku/cli/status.py, renku/core/commands/checks/__init__.py, renku/core/commands/checks/datasets.py, renku/core/commands/checks/external.py, renku/core/commands/dataset.py, renku/core/commands/format/graph.py, renku/core/commands/graph.py, renku/core/compat.py, renku/core/errors.py, renku/core/management/datasets.py, renku/core/management/storage.py, renku/core/models/cwl/command_line_tool.py, renku/core/models/cwl/types.py, renku/core/models/datasets.py, renku/core/models/provenance/activities.py, tests/cli/test_datasets.py
To add an external file to a dataset pass `--external` option to the `dataset add` command. To check for modification in external files run `renku dataset update --external`.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/815
=> feat(dataset): adding data from external files without copy

conftest.py, renku/core/commands/dataset.py, renku/core/management/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
When the repo is dirty some renku commands (e.g. `renku dataset add`) commit all the dirty changes when finished. This PR fixes this issue by committing only files that are modified by the command.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1108
=> fix(dataset): commit only dataset files

renku/cli/dataset.py, renku/core/commands/dataset.py, tests/cli/test_integration_datasets.py
Can avoid download confirmation prompt when importing a dataset by passing `-y` or `--yes`.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/915
=> feat(dataset): bypass import confirmation

renku/core/management/storage.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_cli.py
Running renku with `--no-external-storage` was still tracking files in LFS which will be fixed by this PR.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1129
=> fix(dataset): --no-external-storage flag not working

renku/core/management/datasets.py, tests/cli/test_integration_datasets.py
closes: #1118
Even though this fixes the reported issue in an acceptable manner, UX experience remains unaddressed. Ticket for the UX part is still here #1082 and in this case its very clear that we should put more attention to the UX of this progress bar. On my machine progress bar disappears so fast that for a majority of the time I have a perception that the process is hanging even though it's working hard to import the data.
=> fix(datasets): fixed importing large amount of small files

renku/core/management/datasets.py, tests/cli/test_datasets.py
Avoids recursive addition of a dataset's data directory to it.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1042
=> fix(dataset): avoid recursive addition of data directory

renku/cli/dataset.py, renku/core/commands/dataset.py, renku/core/errors.py, renku/core/management/datasets.py, renku/core/models/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py
Adding existing data to a dataset will fail the whole operation. This PR changes this behavior by adding only non-existing files instead of failing. You can overwrite existing files by passing a `--overwrite` flag.
Moreover, the `-d` flag is refactored to always be used as a directory instead of depending on the input type.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1149
=> feat(dataset): no failure when adding existing files

renku/cli/clone.py, renku/core/commands/clone.py, renku/service/entrypoint.py, renku/service/views/cache.py, tests/cli/test_integration_datasets.py
This PR refactors core API `renku_clone` to more descriptive name `project_clone`.
=> chore: refactor renku_clone to project_clone

renku/service/jobs/datasets.py, renku/service/serializers/datasets.py, renku/service/views/datasets.py, tests/cli/test_integration_datasets.py, tests/cli/test_move.py, tests/service/jobs/test_datasets.py, tests/service/views/test_dataset_views.py, tests/service/views/test_utils.py, tests/utils.py
This PR adds consistency between service and the core in regards with `dataset_name` => `short_name` and adds support for adding title on dataset creation. 
addresses: #1075 
addresses: #1148
Rebase for #1186 is needed after merging this PR.
=> refactor: replaces dataset_name with short_name & title support

renku/core/commands/dataset.py, renku/core/models/datasets.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py
Set dataset's URL to be always equal to its `_id`.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1057
=> fix(dataset): correct url in different domain

renku/core/commands/providers/doi.py, renku/core/utils/doi.py, tests/cli/test_integration_datasets.py
The following cases will work now:
```
renku dataset import www.doi.org/10.7910/DVN/WTZS4K
renku dataset import http://dx.doi.org/10.7910/DVN/WTZS4K
renku dataset import https://www.doi.org/10.7910/DVN/WTZS4K
...
```
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1078
=> feat(dataset): doi variations for import

conftest.py, renku/cli/config.py, renku/cli/move.py, renku/cli/run.py, renku/core/commands/dataset.py, renku/core/commands/echo.py, renku/core/commands/providers/dataverse.py, renku/core/commands/providers/doi.py, renku/core/commands/providers/zenodo.py, renku/core/management/datasets.py, renku/core/management/storage.py, renku/core/models/cwl/command_line_tool.py, tests/cli/test_datasets.py, tests/cli/test_isolation.py, tests/cli/test_rerun.py, tests/cli/test_update.py, tests/core/commands/test_cli.py
This adds warning messages when files get added to LFS like:
```
Warning: Adding files to Git LFS:
file.txt
To disable this warning in the future, run:
renku config show_lfs_warnings False
```
This PR also fixes output redirection in `renku run`. Before, when doing something like `renku run command >out.txt 2>err.txt`, not just the output of command would get passed into the files, but also any renku specific messages (like errors, warnings etc.). With this PR, the output redirection is only applied to the subprocess call, and renku itself can log to the terminal normally. Note: this doesn't work on windows, where the old behaviour is still in place.
This PR also fixes a bug where dataset files would always get added to LFS, even if the user didn't have/want LFS.
Closes #1099
=> feat(cli): Adds warning messages for LFS, fix output redirection

Pipfile.lock, setup.py
=> build(deps): Fix failing CI due to new flake8 version 3.8

conftest.py, pytest.ini, renku/cli/storage.py, renku/core/management/git.py, renku/core/management/storage.py, tests/cli/test_move.py, tests/core/commands/test_storage.py
Adds a new `renku storage clean <files>` command that removes locally cached LFS content (replaces it with pointer file content).
Closes #1147
=> feat(core): Adds renku storage clean command

renku/service/cache/models/job.py, renku/service/jobs/datasets.py, renku/service/serializers/datasets.py, renku/service/utils/__init__.py, renku/service/views/datasets.py, tests/service/views/test_dataset_views.py
closes: #1190 
This PR adds a feature for handling failures to sync with remote repositories. In case of such failures, it will create a new branch (named by generating `uuid4()` ) and push it to a remote. Because of this behaviour, we add to responses of `datasets.add` and `datasets.create`. In cases where we sync with remote within jobs, this `remote_branch` key will be written inside of job details which can be accessed via `/jobs`.
Additional key in HTTP responses can be found in:
```
{
...
"remote_branch": "d059c132512846e88aa642e88a1bf6e2"
...
}
```
or in case of a job details:
```
{
...
"extras": {
"remote_branch": "d059c132512846e88aa642e88a1bf6e2"
}
...
}
```
=> feat: protected branches support

run-tests.sh
Ignores eggs in shellcheck - we don't write those scripts so we shouldn't be checking them. 
This should allow #1251 to pass.
=> chore: ignore eggs in shellcheck

tests/core/commands/test_doctor.py
Fixes a failing renku-doctor test by using non-conflicting extension for test file.
=> chore: fix lfs doctor test

renku/cli/__init__.py, renku/cli/dataset.py, renku/core/commands/dataset.py
Removes `--datadir` flag since it's not working/implemented, to be picked up again in #1284 
Removes `--renku-home` flag, we don't want it to be set to something other than `.renku`, there's really no reason to, and in most places in the code it's hardcoded anyways
Not removing `--path`, since that seems to work fine in my tests (But it has to be specified in the beginning, `renku --path . dataset`, not `renku dataset --path .`). Not sure how useful that is, but it works and there might be cases where it's useful.
Closes #1197
=> fix(cli): Remove --datadir and --renku-home

renku/core/management/migrate.py
Makes it so `.renku/metadata,yaml` is only committed/updated if there were migrations to execute.
Closes #1296
Followup issue: https://github.com/SwissDataScienceCenter/renku-python/issues/1307
=> fix(core): Only update project metadata if any migrations were executed

renku/service/config.py
Fixes integration tests on macOS. On macOS `/var` is a symlink to `/private/var` which can cause issue if at some point we resolve a path.
=> fix(tests): integration tests

renku/core/management/migrations/m_0005__2_cwl.py
Fix use of absolute paths in workflow migrations which show up when migrating a client within a client (e.g. when importing from renku repo).
=> fix(core): fix paths in migration of workflows

.github/workflows/test_deploy.yml, Pipfile.lock, conftest.py, run-tests.sh, setup.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/cli/test_run.py
This PR makes a few improvements on our testing setup:
* import datasets tests use 60x times smaller datasets for importing
* `integration` marked tests now run in parallel using `pytest-xdist` ( normal unit tests are still running sequentially due to flakiness, but by component)
* local execution of `pytest -m integration -n auto` leads to the execution time of <5 minutes (depends on the CPU/Threads count)
* speeds up CI execution (4 workers only, expandable with our infrastructure if we want faster):
* `test-macos` & `test-linux`: ~20min (was ~40min)
* `test-linux-integration`: ~15min (was 45min)
* `test-macos-integration`: ~20min (was ~55min+) 
* overall: ~25min (was ~55+min with collect & provisioning)
* unit tests are decoupled on the CI level so testing happens for each module …
=> test: core IT migrated & performance improvements

renku/cli/init.py, tests/cli/test_init.py
Includes list of existing files (hidden files too)  in the error message when trying to initialise a non-empty directory.
Fixes #1387
=> feat(cli): show existing paths when initializing non-empty dir

renku/core/management/migrations/m_0003__2_initial.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/models/workflow/run.py
Adds deterministic id's for migrate `renku:Run`s. The id's are now based on the hash of the original `*.cwl` path and its commit.
Closes #1532
=> fix(core): fix workflow migration triples

Dockerfile.cli
libxslt was installed in a stage of the docker build that was not copied over to the final stage.
Closes #1513
=> fix(cli): fixes libxslt dependency in docker image

renku/core/commands/dataset.py, tests/cli/test_integration_datasets.py
Preserves original dataset's directory hierarchy when importing a renku dataset. If dataset includes files that were not in its data directory, those files will be copied to the root of its new data directory.
Fixes https://github.com/SwissDataScienceCenter/renku-python/issues/1550
=> fix(dataset): broken directory hierarchy for renku imports

conftest.py, renku/core/commands/providers/renku.py, renku/core/errors.py, tests/cli/test_integration_datasets.py
Don't raise an exception if a dataset is referenced from a project in the KG that does not exist on gitlab anymore.
closes #1569
=> fix(core): fix importing a dataset referenced from non-existent projects

renku/core/commands/graph.py, renku/core/management/git.py, renku/core/management/migrations/m_0005__2_cwl.py, renku/core/models/cwl/command_line_tool.py, renku/core/models/provenance/activities.py, renku/core/models/provenance/qualified.py, renku/core/utils/scm.py, tests/cli/test_datasets.py
Git encodes path with unicode characters, like `filé.txt` as `"fil\u00e9.txt"`. This undoes that encoding when loading file paths from gitpython.
Closes #1474
=> fix(core): fixes git encoding of paths with unicode characters

renku/core/management/repository.py, tests/core/commands/test_client.py
the `remote_cache` class attribute was getting shared between `LocalClient` instantiations in the service, causing duplicate project `@id`s
=> fix(core): fix bug where remote_cache caused project ids to leak

renku/core/commands/graph.py
fixes a bug where `rerun` would not rerun all steps if one of the output paths of a step was a subpath of an output of a previous step.
E.g. step1 -> `hello` and step2 -> `hello.wc`
=> fix(core): Fix graph building for nodes with same subpath

renku/core/commands/dataset.py, tests/cli/test_datasets.py
Do not commit if nothing is edited in a dataset.
Fixes #1705
=> fix(dataset): no commit if nothing is edited

.github/workflows/test_deploy.yml
=> fix: replace deprecated set-env commands in the github actions

renku/core/management/clone.py, tests/cli/test_integration_cli.py, tests/cli/test_integration_datasets.py
Print clean git error message when `renku clone` fails.
Fixes #1715
=> feat(cli): better error message for renku clone

renku/core/commands/save.py, renku/core/errors.py, renku/core/management/git.py, tests/cli/test_save.py
Includes staged files in `dirty_paths` logic.
Saves staged files along unstaged ones if called without paths.
Raises exception if called with paths but staged paths not included in command.
Closes #1692
=> fix(core): fixes renku save with staged changes

conftest.py, renku/cli/exception_handler.py, renku/cli/migrate.py, renku/core/commands/migrate.py, renku/core/utils/contexts.py, renku/data/pre-commit.sh, tests/cli/test_migrate.py, tests/core/commands/test_cli.py
Print proper message in git pre-commit hooks when project version is unsupported or requires a migration.
Fixes #1697
=> fix(core): pre-commit hook message for unsupported project

Dockerfile.svc
This fixes the broken docker image where the main service failed to start. 
Follow up issue to improve on this: https://github.com/SwissDataScienceCenter/renku-python/issues/1751
The image is deployed on https://rok.dev.renku.ch
=> chore: revert to editable service install

.dockerignore, Dockerfile.svc, chartpress.yaml
This is hopefully the last in the series of "quick fix to dirty version" PRs. 
The solution was a bit more involved than previously thought - because we use `chartpress` to publish our images and because `chartpress` modifies some files in the repo before building the image, it will necessarily result in a "dirty" version of the installed package. I circumvent this here by introducing a docker build argument which can be set to in order to `git reset --hard` the repo before the installation in the `Dockerfile`. The default behavior is still to build with the local (uncommitted) changes in order to not surprise any unsuspecting developers who might be otherwise left wondering what happened to their code in the docker image. 
To test:
```
$ chartpress
$ docker run --rm -ti --entrypoint bash …
```
=> chore: fix dirty version on chartpress build

renku/cli/__init__.py, renku/cli/migrate.py, renku/core/management/repository.py, tests/cli/test_migrate.py
adds a `renku migrationscheck` command that produces output of the form
```
{
"latest_version": "0.12.2.dev11+dirty", 
"project_version": '"0.12.2.dev11+dirty", 
"migration_required": false,
"project_supported": true, 
"template_update_possible": false, 
"current_template_version": "0.12.2.dev11+dirty", 
"latest_template_version": "0.12.2.dev11+dirty", 
"automated_update": false, 
"docker_update_possible": false
}
```
Closes #1760
=> feat(cli): add migrationscheck command

helm-chart/renku-core/templates/deployment.yaml, helm-chart/renku-core/values.yaml
This PR adds the `GIT_LFS_SKIP_SMUDGE=1` environment variable to the service containers to prevent pulling LFS data when not needed. The operations that require LFS objects do so explicitly anyway (e.g. dataset import from renku projects). This significantly improves the performance of common operations like `dataset.list`.
=> chore: do not pull LFS in service

Dockerfile.svc, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/templates/deployment.yaml, helm-chart/renku-core/values.yaml
this PR allows the renkulab admin to set the gunicorn worker config via helm values. 
~~edit: I can't get the values to work if I pass them via `--set core.nWorkers=4` with `helm`, for example... but they work if I set them in the values file~~
=> chore(service): specify gunicorn config via values

renku/cli/config.py
Update the documentation around `renku config` to include the full list of supported options.
It was pointed out that there isn't a docs page for that in renku, and this seems to be the best place where to add this information now that both `renku` and `renku-python` docs are unified.
Any reference to the `registry` config has been removed since it's not used anywhere and it was used in the examples.
If you prefer to keep it there for any reason, feel free to push changes directly to this PR or to request the change.
re SwissDataScienceCenter/renku#1647
=> docs: update renku config documentation

Dockerfile.svc, helm-chart/renku-core/values.yaml
Sets the default to use threading so the service can respond to k8s probes while serving requests.
=> chore: use sensible defaults for worker parallelism

.github/workflows/test_deploy.yml, renku/data/pre-commit.sh, tests/cli/test_datasets.py, tests/core/commands/test_cli.py
Fixes locale problem with pytest, gitpython, click and python3.6
Fixes GitHookException stdout in case where messages are too long.
=> test: fix git commit hook tests on python3.6

.github/workflows/pipfile-update.yml
Apparently the branches-ignore keyword does not apply to the originating branch of a PR but to the target branch of a PR
=> chore: fix exclusion of pipfile lock action from dependabot PRs

Pipfile.lock, conftest.py, renku/cli/graph.py, renku/core/commands/dataset.py, renku/core/incubation/graph.py, renku/core/management/datasets.py, renku/core/management/migrate.py, renku/core/management/migrations/m_0003__1_jsonld.py, renku/core/management/migrations/m_0003__2_initial.py, renku/core/management/migrations/m_0004__submodules.py, renku/core/management/migrations/models/v3.py, renku/core/management/migrations/models/v8.py, renku/core/management/repository.py, renku/core/models/datasets.py, renku/core/models/jsonld.py, renku/core/models/provenance/datasets.py, renku/core/models/provenance/provenance_graph.py, renku/core/utils/migrate.py, renku/core/utils/urls.py, setup.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_client.py
Parses git history and puts all datasets' metadata in a single file: `.renku/dataset.json`. To generate this file use: `renku graph generate-dataset`. To export add `-d` flag to the export command: `renku graph export -d --format jsonld`.
Fixes #1710
=> feat(dataset): dataset provenance in a single file

renku/core/models/git.py, tests/core/models/test_git.py
Fixes issue with RE string concatenation when one part is `None`
=> fix(core): fix gitlab url parsing when GITLAB_BASE_URL is set without port

.github/workflows/test_deploy.yml, conftest.py, renku/core/commands/save.py, tests/service/jobs/test_jobs.py, tests/service/views/test_cache_views.py, tests/service/views/test_dataset_views.py
Reset service cache state if pushing to remote branch fails. The push will be done to another remote branch which its name is returned as `remote_branch` in the JSON response.
Fixes #1795 
Fixes #1794
=> fix(service): reset cache after failed push

.github/workflows/acceptance-tests.yml
Adds an action to automatically deploy renku to a clean namespace and run acceptance tests. Only runs on PRs that affect the service. 
Points left to do:
1. determine when this should run
2. how to do the teardown
For 1. it was discussed that this should run on all PRs that push changes to `service` and `core` but to not be required for PRs to pass because of possible issues with dependencies with other components. It should also run on `master` and tags. 
For 2. I would leave it as it is done in the main renku repo atm, which is that the deployment gets destroyed after the PR is closed. But maybe in the near future this should change to doing a `helm uninstall` if the tests pass to release some of the resources followed by a namespace delete after the PR is merged. If we delete the …
=> chore: add acceptance test action

conftest.py, renku/cli/graph.py, renku/core/incubation/graph.py, renku/core/management/datasets.py, renku/core/management/repository.py, renku/core/models/provenance/datasets.py, renku/data/new_graph_shacl_shape.json, tests/cli/test_datasets.py, tests/cli/test_graph.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_client.py
Use `renku graph generate` to generate new graph metadata for both workflows and datasets. Use `renku graph export` to generate triples for workflows and datasets.
=> refactor(core): unify new graph generation

conftest.py, renku/service/cache/models/project.py, renku/service/controllers/cache_list_projects.py, renku/service/controllers/templates_create_project.py, renku/service/controllers/utils/project_clone.py, renku/service/utils/__init__.py, renku/service/views/decorators.py, tests/service/controllers/test_templates_create_project.py, tests/service/controllers/utils/test_project_clone.py, tests/service/jobs/test_datasets.py, tests/service/jobs/test_jobs.py, tests/service/views/test_cache_views.py
This PR changes old caching path of 
```
CACHE_PROJECTS_PATH / self.user_id / self.owner / self.name
```
to 
```
CACHE_PROJECTS_PATH / self.user_id / self.project_id / self.owner / self.name
```
This improves couple of things:
- Prevents potential concurrent problems (in case of errors) which could arise due to the nature of cloning the same project by the same user multiple times in parallel. 
- Easier debugging time. Since project_id is the identifier for the Project model instance and contains project metadata stored in the cache, having this reference also on the filesystem pointer makes debugging concurrent problems easier.
- If the project got deleted and re-cloned it will have new generated `project_id` and this property will be visible immediately by inspecting the filesystem.
=> fix: use project_id as part of project filesystem path

renku/core/models/provenance/provenance_graph.py
If the ProvenanceGraph.custom_bindings property is being set, the `rdflib.ConjunctiveGraph.bind` function is called with `replace=True` function argument. This is only available in rdflib==5.0.0 or later.
Fixes #1882
=> fix: rdflib.ConjunctiveGraph.bind API of 4.2.2

renku/core/commands/providers/renku.py, renku/core/management/datasets.py
Make dataset import more resilient to errors. Move files instead of copying to preserve disk space.
Fixes #1741 
Fixes #1879
=> fix(dataset): import renku datasets

renku/core/management/git.py, renku/core/management/storage.py, renku/core/utils/git.py, tests/core/management/test_storage.py
Prevents `.renku` directory from being tracked in LFS.
Fixes #1866
=> feat(core): exclude renku metadata from lfs

renku/cli/save.py, renku/core/commands/save.py, tests/cli/test_save.py
closes #1726 
Draft for now. needs the command builder refactoring so we can use the communication library to prompt for resolving merge conflicts.
=> fix(core): fixes save and push to correctly handle merge conflicts

Pipfile.lock, renku/cli/exception_handler.py, renku/core/management/config.py, setup.py, tests/cli/fixtures/cli_kg.py, tests/cli/fixtures/cli_repository.py, tests/cli/test_config.py
Set `$HOME` to a temporary directory on the `repository` fixture. Adds exclusive write, shared read locking for the `~/.renku/renku.ini` file.
closes #1936
=> chore: mock user home and fix renku config concurrency issues

renku/core/commands/save.py, renku/core/models/git.py, renku/service/controllers/api/mixins.py, tests/service/fixtures/service_integration.py, tests/service/jobs/test_project.py, tests/service/views/test_cache_views.py, tests/service/views/test_exceptions.py
Tries to do a `git fetch && git reset --hard origin` before executing an operation on the cache to ensure the cache is in sync.
Meant as a band-aid until porcelain commands are done and the UI switched over to them.
=> fix(service): sync cache with remote before operations to prevent cache getting out of sync

renku/cli/service.py, tests/cli/test_service.py
Adds a ping check before executing service commands through the CLI. In case redis is not found running, we show nice message to the user instead of panicking.
=> chore: add better user messaging on service api start error

renku/cli/dataset.py, renku/cli/exception_handler.py, renku/cli/move.py, renku/core/commands/move.py, renku/core/management/datasets.py, renku/core/management/git.py, renku/core/management/repository.py, renku/core/management/storage.py, renku/core/models/cwl/command_line_tool.py, renku/core/models/datasets.py, tests/cli/test_move.py, tests/core/commands/test_client.py, tests/core/fixtures/core_datasets.py, tests/fixtures/common.py
Completes `renku mv` command by covering corner cases and fixing potential bugs. It also adds a `--to-dataset` flag that allows moving files from source datasets (determined by paths) to a destination dataset.
Fixes #1911 
Fixes #1159
=> feat(dataset): mv command

conftest.py, docs/commands.rst, renku/cli/__init__.py, renku/cli/login.py, renku/core/commands/login.py, renku/core/commands/options.py, renku/core/commands/providers/renku.py, renku/core/management/config.py, renku/core/utils/urls.py, tests/cli/fixtures/cli_gateway.py, tests/cli/fixtures/cli_kg.py, tests/cli/test_login.py
Adds a `renku login` command that communicates with Renku's gateway and receives and stores an oauth access token. ATM, this token is used when sending request to access KG.
Fixes #677
=> feat(core): renku login

renku/core/commands/dataset.py, renku/core/commands/providers/__init__.py, renku/core/commands/providers/api.py, renku/core/commands/providers/dataverse.py, renku/core/commands/providers/doi.py, renku/core/commands/providers/olos.py, renku/core/commands/providers/renku.py, renku/core/commands/providers/zenodo.py, renku/core/management/datasets.py, renku/core/utils/git.py, renku/service/jobs/datasets.py, renku/service/jobs/project.py, tests/cli/test_integration_datasets.py, tests/service/jobs/test_datasets.py
Service passes its gitlab token to renku core when importing a renku dataset from the same deployment. The token is used in renku core to access KG and to clone project that contains the dataset.
Fixes #1962
=> feat(service): pass auth info to core

renku/core/commands/init.py, renku/service/controllers/templates_create_project.py, renku/service/serializers/templates.py, tests/service/controllers/test_templates_create_project.py, tests/service/views/test_templates_views.py
Fixed git user not being set in newly created project.
Also fixes `owner` being taken from the template repository (e.g. `SwissDataScienceCenter` instead of the actual project namespace)
Now returns `project_id` in the `templates.create_project` request. As the project is in cache anyways, I don't understand why this wasn't returned before.
/deploy
=> fix(service): fix service project creation

.dockerignore, Dockerfile.svc, README.rst, docker-compose.yml, entrypoint-svc.sh
This PR modifies the image of the renku core service to enable live service reloads to make development a more pleasant experience. It also makes sure that the image build is split up sufficiently to prevent reinstalling/rebuilding of dependencies when this is not necessary. A follow-up to this PR should turn this into a proper two-stage build in order to also reduce the final image size. 
/deploy
=> chore: enable service reloading in debug mode

docs/gensidebar.py, docs/service.rst, renku/cli/service.py, renku/service/config.py, renku/service/entrypoint.py, renku/service/views/apispec.py, renku/service/views/cache.py, renku/service/views/datasets.py
This PR fills in several of the API docstrings to add missing schemas. It also adds a description of the API including the response codes. 
closes #2056 
/deploy #notest
=> chore(service): improve api docs

renku/service/jobs/cleanup.py, renku/service/scheduler.py
Redis File entries that weren't deleted (probably due to restarting the service but not clearing redis cache) will now be properly deleted.
Job timeout for management jobs have been adjusted to not run longer than until the next instance of the job.
closes #2085
=> fix(service): fixes management jobs running into timeouts

renku/core/commands/init.py, renku/service/controllers/templates_create_project.py, setup.py, tests/service/controllers/test_templates_create_project.py
Do not remove from the template parameters - just warn user - that are not explicitly specified in metadata. moreover, internal parameters like `__parameter__` should not be exposed to the user.
=> fix(core): do not remove unused template parameters

renku/cli/__init__.py, renku/cli/login.py, renku/core/commands/dataset.py, renku/core/commands/login.py, renku/core/commands/providers/renku.py, renku/core/management/clone.py, renku/core/management/datasets.py, renku/core/utils/git.py, renku/core/utils/urls.py, tests/cli/fixtures/cli_projects.py, tests/cli/test_login.py, tests/cli/test_save.py, tests/core/commands/test_storage.py
Allows log into private repos by using `renku login --git endpoint`. It changes project's remote URL to a `<endpoint>/repo/...` URL which will authenticate gitlab server accesses through the renku gateway. Original remote URL will be saved in a remote with name `renku-backup-<remote-name>`. Logout will restorer the original remote URL.
Fixes #1892
=> feat(core): git login from CLI

.dockerignore, Dockerfile.cli, Dockerfile.svc, entrypoint-svc.sh
* Change from alpine to slim to take advantage of pre-built wheels. 
* Use a two-stage build for the service to reduce image size
* Remove the `debug` group since it's not needed because code isn't running in editable mode
/deploy
=> chore: update image builds; use slim

.github/workflows/test_deploy.yml, .github/workflows/test_publish.yml
remove the hardcoded `master` branch as default branch of the renku-python repository and rely on github.event information
=> chore(core): use github.event's information to figure out default branch name

renku/version.py.tmpl
With the current version template the generated `version.py` fails passing linting constraints. this patch is addressing those warnings.
=> fix(core): version template lint

renku/core/commands/cwl_runner.py, tests/cli/test_rerun.py
=> fix(core): CWL to work with filenames with spaces

.github/workflows/acceptance-tests.yml, .github/workflows/test_deploy.yml
Renku github actions have been moved to https://github.com/SwissDataScienceCenter/renku-actions so we need to update the references. 
/deploy
=> chore: update renku action paths

renku/core/management/config.py, tests/cli/test_config.py
The `test_config_write_concurrency` test used to fail often because the operation to test was very quick and trying to start many at the same time wasn't always enough.
The new test now monkey patches the write operation to introduce a slowdown, making the result deterministic.
P.S. I tried another solution using [site](https://docs.python.org/3/library/site.html) but I couldn't get a working test in a reasonable amount of time. Also, that solution was going to be more complicated and harder to debug should the test fail in the future due to some code change.
=> test: make config write concurrency test deterministic

renku/cli/status.py, renku/core/commands/status.py, renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/metadata/database.py, renku/core/metadata/gateway/database_gateway.py, renku/core/utils/os.py, tests/cli/test_status.py, tests/core/fixtures/core_database.py, tests/fixtures/repository.py, tests/utils.py
Allows specifying files paths when calling `renku status` to limit the scope to only those paths. A path can be both input and output. If an outdated activity has no generation, we will show the activity id along with modified input(s).
Fixes #2260
=> feat(core): show status for specific paths

renku/core/models/provenance/activity.py
`Activity` annotations are coming from plugins. There could be multiple plugins for activity annotations as well as one plugin could produce multiple annotation for a single `Activity`. This patch basically just flattens the list of annotations in order to have it stored correctly in the metadata storage backend
=> fix(core): activity annotation

renku/core/commands/dataset.py, renku/core/commands/format/dataset_tags.py, renku/core/management/dataset/datasets_provenance.py, renku/core/management/dataset/tag.py, renku/core/management/migrations/utils/conversion.py, renku/core/metadata/gateway/dataset_gateway.py, renku/core/models/dataset.py, renku/data/shacl_shape.json, tests/cli/test_datasets.py
Removes `schema:location` from `schema:PublicationEvent` SHACL shape. Removes `sh:lessThanOrEquals` constraint from Dataset's `schema:dateCreated`.
=> fix(dataset): fix shacl shape for datasets

renku/core/commands/dataset.py, renku/core/management/migrations/models/v9.py, renku/core/models/calamus.py, renku/core/models/dataset.py, renku/core/models/project.py, renku/core/utils/datetime8601.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/cli/test_migrate.py, tests/cli/test_rerun.py, tests/cli/test_update.py, tests/utils.py
Unset `schema:dateCreated` for imported datasets. Remove microseconds from datetime fields so that the exported format will be for example like `2021-09-16T12:13:35+00:00` (and not `2021-09-16T12:13:35.540364+00:00`)
=> fix(dataset): unset date_created after import

.github/workflows/test_deploy.yml
macOS CI image changed and got `git-lfs` brew package installed by default.
This basically caused an error when trying to install the pin git-lfs version with brew.
=> fix(core): unlink git-lfs package if installed on macos CI image

renku/core/management/workflow/plan_factory.py, renku/data/shacl_shape.json
in one scenario (generated output from script) the `CommandOutput`'s `encoding_format` parameter is not set currently in the metadata that will cause errors when trying to run with CWL backend (current default).
This bug has been found by @gavin-k-lee see: https://renkulab.io/gitlab/lee.gavin.k/debug-workflow repo for the workflows
=> fix(core): encoding format for output

renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/management/migrations/models/v9.py, renku/core/management/migrations/utils/__init__.py
closes #2463 
Loading metadata code did not pass LocalClient, which in turn didn't set creator from git if it was missing. This makes sure LocalClient is passed in all relevant places.
=> fix: set missing creator when migrating projects

.github/workflows/acceptance-tests.yml, .github/workflows/test_deploy.yml, .github/workflows/test_publish.yml, renku/core/commands/providers/dataverse.py, renku/core/commands/providers/dataverse_metadata_templates.py, renku/service/controllers/cache_migrations_check.py, renku/service/controllers/utils/project_clone.py, renku/service/controllers/version.py, renku/service/serializers/version.py, renku/service/views/api_versions.py, renku/service/views/apispec.py, renku/service/views/cache.py, renku/service/views/config.py, renku/service/views/datasets.py, renku/service/views/graph.py, renku/service/views/jobs.py, renku/service/views/templates.py, renku/service/views/version.py, setup.py, tests/cli/fixtures/cli_repository.py, tests/cli/test_integration_datasets.py, tests/cli/test_migrate.py, tests/cli/test_save.py, tests/service/views/test_cache_views.py, tests/service/views/test_graph_views.py, tests/service/views/test_version_views.py
Backport of the versioned service endpoints (/0.9/.... URLs) to 0.16.2
closes #2433
=> feat(service): backport API versioning changes from 1.0.0 release

renku/core/commands/status.py, renku/core/commands/update.py, renku/core/commands/workflow.py, renku/core/management/interface/activity_gateway.py, renku/core/metadata/database.py, renku/core/metadata/gateway/activity_gateway.py, renku/core/metadata/gateway/database_gateway.py, renku/core/utils/metadata.py, tests/cli/fixtures/cli_runner.py, tests/cli/test_update.py, tests/core/metadata/test_activity_gateway.py
Adds an index of (generations...):lastest_activity and uses that for checking `renku status` and `renku update`
=> fix(core): make status and update consider all relevant activities

tests/cli/test_integration_datasets.py
Some test actually depended on requirements-devel.txt, a file that was otherwise irrelevant. I switched it to use poetry.lock instead.
=> chore: fix IT due to deleted requirements-devel.txt

poetry.lock, renku/core/metadata/database.py, renku/core/metadata/gateway/database_gateway.py
Prevents OOBucket, OOSet, OOTreeSet and BTree.Length from being stored in separate files.
Reduces files generated in renku metadata by a factor of ~15 (depends on the project)
=> fix(core): prevent catalog from creating tons on separate files

poetry.lock, renku/core/management/storage.py
git-lfs version 3.0.2 made some changes so the `git lfs migrate info` command, which is supposed to output files not in LFS that should be in LFS now also returns the "helpful" entry `LFS Objects    0 B       0/1 files(s)      0%`. This PR ignores that when processing LFS files.
=> fix(core): fix regression due to git-lfs version 3.0.2

.github/workflows/test_deploy.yml
The poetry-publish action doesn't work as it uses an older version of pip, instead, just call poetry manually.
=> chore: fix poetry deploy action

renku/core/metadata/repository.py
Sometimes, git ls-tree returns more than the paths that were sent to it, for some reason. This fixes it.
=> fix(core): fix hash calculation when git returns too many paths

renku/cli/migrate.py, renku/core/commands/migrate.py, renku/core/management/dataset/datasets_provenance.py, renku/core/management/migrate.py, renku/core/management/migrations/m_0009__new_metadata_storage.py, renku/core/management/migrations/utils/__init__.py, renku/core/models/dataset.py, tests/cli/fixtures/cli_old_projects.py, tests/cli/test_migrate.py
Adds an `--preserve-identifiers` flag to the `migrate` command which keeps original datasets' identifiers when migrating. This option is intended only for KG during indexing to keep the identifiers consistent with the project's metadata.
Fixes #2511
=> fix(core): preserve dataset ids for KG migrations

.readthedocs.yaml, docs/requirements.txt
fixes poetry build not working due to editable flag.
Built here: https://renku.readthedocs.io/projects/renku-python/en/fix-rtd-poetry/introduction.html
=> docs: fix RTD build with poetry

renku/core/management/migrations/models/v9.py
Fixes kg issue 2 with project eawagrs/lake-greifen-profiles, namely:
```
File "<attrs generated init renku.core.management.migrations.models.v9.Project>", line 23, in __init__;
self.__attrs_post_init__();
File "/usr/lib/python3.8/site-packages/renku/core/management/migrations/models/v9.py", line 169, in __attrs_post_init__;
self.client.repository.get_previous_commit(self.client.database_path, first=True);
File "/usr/lib/python3.8/site-packages/renku/core/metadata/repository.py", line 298, in get_previous_commit;
raise errors.GitCommitNotFoundError(f"Cannot find previous commit for '{path}' from '{revision}'");
renku.core.errors.GitCommitNotFoundError: Cannot find previous commit for '/tmp/lake-greifen-profiles-6123667132990583931/.renku/metadata' from 'HEAD';
```
=> fix(core): fix project creator path in old project schema

renku/core/commands/run.py, tests/cli/test_run.py
No crash when passing a non-existing command to `renku run`
Fixes #2474
=> fix(core): fail gracefully when running non-existing commands

renku/core/management/dataset/datasets_provenance.py, renku/core/management/migrations/models/v9.py, renku/core/models/dataset.py, tests/cli/test_migrate.py
During a migration, dataset's creation date was set to current date/time instead of the original creation date. This PR fixes this issue and also removed some unused code.
=> fix(core): preserve dateCreated when migrating datasets

renku/core/management/config.py, tests/cli/test_config.py
Interpolation is a non-standard INI feature seems to be only implemented by `ConfigParser`. `GitPython` does not use it either. This PR disables this feature.
Fixes #2486
=> fix(core): disable interpolation when loading/storing renku config

docs/how-to-guides/hpc.rst, docs/how-to-guides/implementing_a_provider.rst, docs/how-to-guides/index.rst, docs/reference/plugins.rst
* cosmetic changes to the docs about the toil provider and workflow plugins. 
* adds workflow plugins to the plugin reference page
=> chore(docs): update provider plugin docs

renku/core/metadata/repository.py, tests/core/metadata/test_repository.py
Removes quotation marks from user's name/email git config.
Fixes #2539
=> feat(core): ignore quotation mark in git user/email config

poetry.lock, pyproject.toml
`shell_complete` kwarg for `click` commands is only available in click 8.0.0 and later.
=> fix(core): require click 8.x

renku/core/models/dataset.py, renku/core/models/provenance/annotation.py, renku/core/models/workflow/composite_plan.py, renku/core/models/workflow/parameter.py, renku/core/models/workflow/plan.py
Our database already supported backwards compatibility (add properties at the class level) and forward compatibility (we're schemaless so additional properties are loaded just fine even if they don't exist in code).
The main issue was that newer properties were lost when editing datasets/plans, as we didn't do a deep copy on editing, causing fields from newer schemas to be lost. Now they are ported/copied to the derived objects properly.
closes #2516
=> feat(core): support forward compatibility of datasets

.github/workflows/test_deploy.yml
templates weren't downloaded in all actions, so depending on which ran first, they might not be included in the cache.
Also, the Makefile has to be used as a cache key, as template version depends on it.
=> chore: fix caching of templates folder with Makefile

renku/core/commands/workflow.py
=> fix(core): provider config parsing in workflow execution

renku/core/models/workflow/plan.py
Fixes #2569
(especially) in case of a `renku workflow iterate`, a `CommandParameterBase` can share the same ID, but with different parameterization, i.e. different `actual_value`.  Hence `Plan::find_parameter` should only be true if both of the case matches (not only the ID)
=> fix(core): Execution graph linking of plans

.github/workflows/test_publish.yml
The publish action was still using `-e` which doesn't work with poetry (until they release version 1.2). This removes -e
=> chore: fix pip install in publish action

CHANGES.rst, helm-chart/renku-core/Chart.yaml, helm-chart/renku-core/templates/configmap.yaml, helm-chart/renku-core/values.yaml
Reverse-proxy NginX in multi core-service deployment has a limited packet size which prevents uploading large files when adding files to datasets in the UI.
This PR makes it accept unlimited messages. We should revert this back once chunked upload is implemented in the service (https://github.com/SwissDataScienceCenter/renku-python/issues/910). 
/deploy renku=1.0-next renku-graph=development renku-ui=master
=> hotfix(service): v1.0.4 unlimited file size in nginx config

renku/core/management/repository.py
=> fix(core): Wipe out .renku directory when initializing

docs/how-to-guides/implementing_a_provider.rst, docs/reference/plugins.rst
This just extends the plugin documentation section with the dummy/example plugin repositories:
- https://github.com/SwissDataScienceCenter/renku-dummy-provider
- https://github.com/SwissDataScienceCenter/renku-dummy-annotator
- https://github.com/SwissDataScienceCenter/renku-cli-plugin-example
- https://github.com/SwissDataScienceCenter/renku-dummy-format
note before merging this PR the linked repositories visibility should be changed to public.
=> docs: add reference to the dummy plugin implementations

.github/workflows/acceptance-tests.yml, .github/workflows/test_deploy.yml
This updates the CI workflows to use the latest actions. It also enhances how the CI deployments are started and deleted.
The setup is as follows:
- if you do not provide `#persist` in the PR description when you specify `/deploy` then the CI deployment is deleted after the acceptance tests complete
- if you provide `#persist` the deployment is kept until the PR is closed.
- when the PR is closed the namespace of the deployment is also deleted
- when the acceptance tests complete AND `#persist` is not used the CI deployment is deleted but the namespace is not deleted in k8s - this makes it possible to reuse the TLS secret and not hit the limits for requesting certs with letsencrypt when the acceptance tests for the same PR are run many times
- artifacts from the acceptance tests are …
=> chore(ci): update to renku actions 0.5.0

pyproject.toml
Keeping duplicate packages in extras definition can cause problems during install. Removing `jinja` so it is installed even when extras are not used.  
closes #2613
=> chore: remove jinja from all

tests/service/controllers/test_templates_create_project.py, tests/service/fixtures/service_client.py, tests/service/views/test_templates_views.py
The fixture has code to cleanup temporary branches, but in 3/4 tests, this wasn't actually called. I've now added it to teardown.
=> test(service): fix cleanup of temporary IT branches

poetry.lock, pyproject.toml
Closes https://github.com/SwissDataScienceCenter/renku-python/security/dependabot/6
Closes https://github.com/SwissDataScienceCenter/renku-python/security/dependabot/5
Closes https://github.com/SwissDataScienceCenter/renku-python/security/dependabot/4
=> fix(service): bump Pillow to 9.0+ to fix security vulnerability

.github/workflows/test_deploy.yml
Automatically merge `master` to `develop` after tagging a new release.
This will keep the tag in the history of the `develop` branch and simplify creating PRs on `master`, overcoming the limitations we have in merging directly to the protected `develop` branch.
=> chore: add action to update develop on tags

.github/workflows/test_deploy.yml
Git LFS 3.1.x breaks our CI due to various issues, this is just a small PR to downgrade LFS to a version that works.
Ubuntu `focal` has git-lfs version 2.9.x, but the `--above` flag that we use was introduced in 2.13.x, so we need to install it from the `jammy` package repo, which has 3.0.2.
=> fix(core): downgrade git-lfs to fix CI

renku/core/commands/view_model/log.py, renku/core/commands/workflow.py, renku/core/management/workflow/providers/toil.py
closes #2697 
Int parameters were set directly in the environment variables, but environment can only contain strings.
There was also a bug with single values being passed to `--map` being treated as list and giving an access error.
Also fixed a bug where old datasets didn't have date_modified, added some fallback dates.
=> fix(core): fix workflow iterate working with int params

CHANGES.rst, helm-chart/renku-core/Chart.yaml
Preparing 0.16.5 on the 0.16-lts branch.
NOTE: The target branch is `0.16-lts`.
=> chore: prep 0.16.5 release

.github/workflows/test_deploy.yml, renku/service/cache/config.py
Two things:
1. Make image and chart publishing run without waiting for tests to pass (the test on this LTS branch are not up-to-date/compatible with new and/or backported changes)
2. Fix a very small style error (that I overlooked in the previous PR - only present in the lts branch)
=> chore: remove CI workflow requirements for publishing

poetry.lock, renku/cli/utils/curses.py, renku/core/commands/view_model/activity_graph.py, renku/core/commands/view_model/text_canvas.py, tests/cli/test_workflow.py
closes #2377 
closes #2574 
Edges belonging to an activity are now colored the same color, with differing colors for overlapping edges, if possible.
Added Plan Name in details view of interactive mode, added `plan` column for `-c` argument, showing plan name in the activity boxes.
Can be tested on https://renkulab.io/gitlab/ralf.grubenmann/test_visualize_2719 run `renku workflow visualize out` or `renku workflow visualize -c plan out`
=> feat(core): color edges on a per-node basis

renku/cli/doctor.py, renku/core/commands/checks/__init__.py, renku/core/commands/checks/datasets.py, renku/core/commands/checks/external.py, renku/core/commands/checks/githooks.py, renku/core/commands/checks/migration.py, renku/core/commands/checks/references.py, renku/core/commands/checks/storage.py, renku/core/commands/checks/validate_shacl.py, renku/core/commands/doctor.py, renku/core/commands/graph.py, renku/core/commands/log.py, renku/core/commands/view_model/log.py, renku/core/management/dataset/dataset.py, renku/core/management/dataset/datasets_provenance.py, renku/core/management/migrations/utils/conversion.py, renku/core/models/dataset.py, tests/cli/test_move.py, tests/core/commands/test_dataset.py, tests/core/commands/test_doctor.py, tests/core/commands/test_log.py, tests/core/fixtures/core_datasets.py
Adds a `--fix` option to the `renku doctor` command and implements a check/fix for datasets that have both `derived_from` and `same_as` set or are derived from themselves. Checks for invalid `derived_from` to avoid crashes in unfixed projects.
Fixes #2725
=> feat(core): add check for invalid imported datasets

.github/workflows/test_deploy.yml
This should allow chart publish action on `0.16-tls` branch to run successfully by:
- Using correct secret name in the chart publish action
- Removing unnecessary `renku` component update action
=> chore: update CI chart publish action

design/003-interactive-session/003-interactive-session.md
add the `renku session` sub-command RFC
=> docs: add renku session RFC

renku/core/management/session/__init__.py
This is for fixing the import error reported by @mohammad-sdsc:
```
___________ ERROR collecting renku/core/management/session/docker.py ___________
312 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/_pytest/runner.py:340: in from_call
313 result: Optional[TResult] = func()
314 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/_pytest/runner.py:371: in <lambda>
315 call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
316 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/_pytest/doctest.py:545: in collect
317 module = import_path(self.path, root=self.config.rootpath)
318 /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/_pytest/pathlib.py:553: in import_path
319 raise …
```
=> feat(core): add missing module init for session package

Makefile, renku/__init__.py, renku/cli/dataset.py, renku/core/commands/view_model/template.py, renku/core/management/template/template.py, renku/core/management/template/usecase.py, renku/core/models/template.py, renku/version.py, tests/cli/test_template.py, tests/fixtures/templates.py
Use template repository's tag as version (instead of the Renku version) for templates bundled with Renku CLI.
Fixes #2714
=> feat(core): consistent template versioning

renku/cli/dataset.py, renku/cli/exception_handler.py, renku/cli/run.py, renku/cli/utils/terminal.py, renku/cli/workflow.py, renku/core/commands/run.py, renku/core/utils/contexts.py, renku/core/utils/os.py, tests/cli/test_graph.py, tests/cli/test_output_option.py, tests/cli/test_rerun.py, tests/cli/test_run.py, tests/core/commands/test_cli.py, tests/fixtures/runners.py, tests/service/fixtures/service_integration.py, tests/utils.py
Adds a `--verbose` flag to the `renku run` command that prints the generated plan after execution.
Fixes #2732
=> feat(workflow): show created plan after renku run

.pre-commit-config.yaml
adds missing ignores/excludes to new pre-commit yaml for pydocstyle
=> chore: fix pydocstyle excludes

renku/service/cache/projects.py, renku/service/controllers/utils/project_clone.py, tests/service/controllers/utils/test_project_clone.py
Clean up the cache properly when cloning a remote repo fails because the repo doesn't exist or it is otherwise not reachable.
fix #2787
=> fix: clean cache after trying to fetch projects from non-existing repos

renku/data/shacl_shape.json, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/cli/test_move.py, tests/cli/test_project.py, tests/cli/test_rerun.py, tests/cli/test_rollback.py, tests/cli/test_run.py, tests/cli/test_template.py, tests/cli/test_update.py, tests/cli/test_workflow.py
=> fix(core): fix SHACL shape for MappingParameter and add SHACL checks to more tests

renku/core/dataset/dataset_add.py, renku/core/util/os.py, renku/core/workflow/plan_factory.py, renku/data/shacl_shape.json, tests/cli/test_run.py, tests/cli/test_update.py
Fixes an error where using external files in `renku run` caused a crash.
Allows orcid.org ids in SHACL.
Fixes #2796
=> fix(workflow): crash with external files in a command

poetry.lock, pyproject.toml, renku/command/graph.py, renku/command/log.py, renku/command/view_model/dataset.py, renku/command/view_model/log.py, renku/core/dataset/dataset.py, renku/core/dataset/dataset_add.py, renku/core/dataset/providers/__init__.py, renku/core/dataset/providers/api.py, renku/core/dataset/providers/dataverse.py, renku/core/dataset/providers/doi.py, renku/core/dataset/providers/models.py, renku/core/dataset/providers/renku.py, renku/core/dataset/providers/zenodo.py, renku/core/management/repository.py, renku/core/workflow/providers/toil.py, renku/data/shacl_shape.json, renku/domain_model/dataset.py, renku/domain_model/provenance/agent.py, renku/ui/api/models/dataset.py, tests/cli/test_datasets.py, tests/core/commands/test_log.py, tests/fixtures/templates.py
Makes `entity` non-Optional in `DatasetFile`: Uses `ProviderRecordSerializerApi::files_info` to pass file information to the import logic and doesn't set `files` on `Dataset` instances.
Refactoring:
* Adds a `ProviderRecordSerializerApi` interface to be inherited in the import providers.
* Removes `attr` in some places
* Providers return a `ProviderDataset` that is a sub-class of `Dataset` but doesn't allow accessing its `files` property.
Fixes #2792
=> chore(refactor): make entity mandatory on DatasetFile

renku/ui/cli/config.py
Remove redundant descriptions of renku.ini fields in docs.
Renku.ini fields are documented under [renku config](https://renku.readthedocs.io/en/latest/renku-python/docs/reference/commands.html?highlight=dataverse.access_token#available-configuration-values) and [directory structure](https://renku.readthedocs.io/en/latest/renku-python/docs/reference/commands.html#available-configuration-values).
* Discard redundant field in the `renku config` section, only keeping those directly related to renku python
* Add a link to [directory structure](https://renku.readthedocs.io/en/latest/renku-python/docs/reference/commands.html#available-configuration-values) for additional fields.
=> docs: rm redundant renku.ini fields

renku/ui/service/gateways/gitlab_api_provider.py
The token passed to the GitLab provider should be an OAuth token, not a private token
=> fix(service): set oauth token instead of private

renku/ui/service/controllers/api/mixins.py, renku/ui/service/errors.py
After looking into this issue, it turns out that adding the `--` mentioned in the error message won't solve the problem. It seems the local repo is somehow out-of-sync with the origin and the branches are not found.
I couldn't find a way to fix it, but purging the local copy seems a good solution to unstuck the user trying to repeat the same action. Otherwise, they seem to be stuck with the same error https://sentry.dev.renku.ch/organizations/sentry/issues/362/events/?project=2&referrer=github_integration
P.S. This fix is not great since it doesn't include a proper test. Sadly, reproducing the issue, or a similar version, was a pain and required manually removing some code -- mocking it would require quite an effort (and the test may not be reliable anyway), probably not worth it for such …
=> fix(service): cleanup project when origin is out of sync

renku/ui/service/scheduler.py
Removes old jobs from the queue before scheduling new ones to avoid duplication. 
=> fix: remove old scheduled jobs

renku/core/session/docker.py
closes #2857 
Copies over `~/.gitconfig` if it exists, otherwise sets environment variables.
=> fix(cli): add git user configuration to local session

.github/workflows/test_deploy.yml, Dockerfile
Fix ci issues with poetry-dynamic-versioning
=> fix(ci): pin poetry-dynamic-versioning to 0.17.1

renku/core/dataset/dataset.py, renku/core/errors.py, renku/ui/cli/dataset.py, tests/cli/test_datasets.py
=> feat(cli): show dataset metadata for tag

renku/command/login.py, renku/core/util/urls.py, tests/cli/test_login.py
This makes it easier to use `read_renku_token` and avoids having to call `parse_authentication_endpoint` separately.
=> chore: propagate use_remote flag up the chain

helm-chart/renku-core/templates/deployment-nginx.yaml
This is messing with the BIT deployment. I don't see why we had to give special capabilities to nginx but @Panaetius  maybe there was a specific reason for this?
I deployed this and everything seems to be fine. The nginx server starts normally.
=> chore(chart): run nginx as non-root

renku/command/checks/__init__.py, renku/command/checks/project.py, renku/command/init.py, renku/core/management/repository.py, renku/domain_model/project.py, renku/ui/cli/init.py, renku/ui/service/controllers/templates_create_project.py, tests/core/commands/test_status.py, tests/service/fixtures/service_client.py, tests/service/views/test_templates_views.py
closes #2937 
Fixes id generation for newly created projects.
For existing projects, `renku doctor --fix` will fix the id. Checked with KG and it shouldn't affect them, as they build the ID themselves based on gitlab.
=> fix(service): correctly use passed namespace in project id generation

renku/command/format/dataset_files.py, renku/core/dataset/dataset.py, renku/core/dataset/tag.py, renku/core/util/metadata.py, renku/infrastructure/repository.py, renku/ui/cli/dataset.py, renku/version.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/core/commands/test_dataset.py, tests/core/fixtures/core_database.py
Allows specifying a tag when running `renku dataset ls-files` that limits the results to those files that are in the given tag.
Fixes #2918
=> feat(dataset): filter ls-files by tag

helm-chart/renku-core/requirements.yaml, helm-chart/renku-core/values.yaml
The latest certificates image and chart can run as non-root.
This is safer than what we had before.
Also the chart and image tags are not tracking each other. This is on purpose.
=> chore: run ca cert injection as non root

docs/reference/api.rst, renku/ui/api/__init__.py, renku/ui/api/graph/__init__.py, renku/ui/api/graph/rdf.py, tests/api/test_rdfgraph.py
Adds an `RDFGraph` object to the API
Usage:
```
from renku.ui.api import RDFGraph
g = RDFGraph()
list(g.subjects(object=URIRef("http://schema.org/Person")))
```
=> feat: add RDFGraph to API

docs/spelling_wordlist.txt, poetry.lock, renku/command/format/workflow.py, renku/command/view_model/activity_graph.py, renku/ui/cli/workflow.py, tests/cli/test_workflow.py
Add a `--format` option on the `renku workflow visualize` command. The output can now be either `console` or `dot`.
Maybe instead of `-i` would it make sense to add an extra format? Something like `console`, `interactive`, `dot`?
-----
This also fixes an error when providing non-existing column names
E.G. `renku workflow visualize <path> --columns aaa ` was triggering
```
renku workflow visualize results.txt --columns aaa 
Ahhhhhhhh! You have found a bug. 🐞
[...]
File "/[...]/renku/command/view_model/activity_graph.py", line 113, in <listcomp>
columns = [ACTIVITY_GRAPH_COLUMNS[c] for c in columns.split(",")]
KeyError: 'aaa'
```
Now it prints 
```
Error: Invalid parameter value for columns 'aaa': you can use any of 'command,id,date,plan'
```
fix #2376
=> feat(workflow): add dot output on workflow visualize

.github/workflows/test_deploy.yml
Since 3.9 is the most common version and we should test with 3.10 as well.
=> chore: change CI test versions of python from 3.7,[3.8,3.9] to 3.9,[3.7,3.10]

docs/reference/models/dataset_provider.rst, renku/core/dataset/providers/dataverse.py, renku/core/dataset/providers/doi.py, renku/core/dataset/providers/factory.py, renku/core/dataset/providers/git.py, renku/core/dataset/providers/local.py, renku/core/dataset/providers/olos.py, renku/core/dataset/providers/renku.py, renku/core/dataset/providers/web.py, renku/core/dataset/providers/zenodo.py, renku/core/plugin/dataset_provider.py, renku/core/plugin/implementations/__init__.py, renku/core/plugin/pluginmanager.py, renku/domain_model/dataset_provider.py
As I am working through #2971 one of the subtasks is to make the dataset providers plugins.
I isolated the changes for this and thought it would be a good idea to submit this PR separately from the rest.
Also wanted to get a feeling of whether my way of going about this is acceptable. I decided to not try to separate `ProviderApi` and the similar importer and exporter abstract classes and try to move some portion of them in the domain_model. But if you think this is necessary then I am happy to do it. 
For now the plugins simply provide the defintion of a specific ProviderApi. And the provider factory is now using pluggy to list all the providers rather than importing what is only locally available.
=> feat(dataset): make dataset providers plugins

.gitignore, .vscode/settings.json
I am ok if people would like this to not be checked in. 
But if we do want it I replicated the stuff from pyproject.toml in the settings.json file.
The most important thing tbh is that vscode properly uses 120 as the line length after using this file.
=> chore: add vscode settings.json

run-tests.sh
Because poetry lockfile sort order is non-deterministic at the moment
=> chore: make poetry lockfile check not required

renku/command/init.py, renku/domain_model/dataset.py, renku/ui/cli/dataset.py, renku/ui/service/controllers/datasets_create.py, renku/ui/service/controllers/datasets_import.py, renku/ui/service/controllers/templates_create_project.py, renku/ui/service/jobs/datasets.py, renku/ui/service/serializers/datasets.py, renku/ui/service/serializers/templates.py, renku/ui/service/views/api_versions.py, tests/service/views/test_dataset_views.py, tests/service/views/test_templates_views.py
closes #3034 
new API version 1.3 (backward compatible)
Adds data dir to `templates.create_project`, `datasets.create` and `datasets.import`
=> feat(service): add support for dataset data directory in endpoints

poetry.lock, renku/core/dataset/dataset.py, renku/core/dataset/providers/renku.py, renku/ui/cli/utils/callback.py
closes #2987 
We can't use `yaspin` / `communication.busy` with subprocess calls that need a prompt, as yaspin will swallow all shell output while it is running.
Also updates communication to allow printing while yaspin is up
=> fix(cli): allow display of ssh password prompt in clone operations

tests/cli/test_rerun.py
if two reruns happened in the same second, renku couldn't create an order between them. this fixes that.
=> test: fixes flaky test with timing issues

.github/workflows/release.yml
Add a manually triggered workflow that creates a release PR and draft release.
Example PR can be seen here: https://github.com/SwissDataScienceCenter/renku-python/pull/3148
Example release draft can be seen here: https://github.com/SwissDataScienceCenter/renku-python/releases/tag/untagged-bd9c50875f99cdb6d673 (please delete once this is merged)
yq does reformat our values.yaml when setting the version, but I think we can live with that.
=> chore: add automated release workflow

tests/service/fixtures/service_integration.py
the branch was deleted in the fixture but the deletion was not pushed to the remote
=> chore: fix cleanup of service test branches

renku/core/util/contexts.py, renku/ui/service/cache/models/project.py, renku/ui/service/cache/projects.py, renku/ui/service/controllers/utils/project_clone.py, renku/ui/service/errors.py, renku/ui/service/utils/__init__.py, renku/ui/service/views/error_handlers.py, tests/service/controllers/utils/test_project_clone.py, tests/service/views/test_cache_views.py, tests/service/views/test_dataset_views.py, tests/service/views/test_templates_views.py
the `ProjectClone` control is called in the base `RenkuOperationMixin`, in which case it wasn't running with the project context and cwd set, which could lead to errors with concurrent requests. This fixes that.
=> fix(service): fix working dir when cloning outside of project_clone view

renku/infrastructure/gateway/plan_gateway.py, tests/cli/test_workflow.py, tests/core/test_plan.py
=> fix(core): fix rerun overwriting plan details with previous versions

.github/workflows/test_deploy.yml
the action to publish the `renku_lock` package didn't work properly with poetry 1.2.x. Other actions seem to work, but just in case, it's probably safer to pin it everywhere until we switch.
=> chore: pin poetry in github actions

renku/command/run.py, renku/core/workflow/plan_factory.py, tests/cli/test_workflow.py
Set Plan's creation date to be equal to Activity's start date.
Fixes #3208
=> fix(workflow): set plan creation date to activity start date

renku/domain_model/git.py, tests/core/models/test_git.py
The `gitlab_re` that we build has an issue with [catastropic backtracking](https://www.regular-expressions.info/catastrophic.html).
essentially, we matched a path like `/~something/owner/repo` and the part that matches `~something`, the part that matches `owner` and the part that matches `repo` were greedy matches for a variable number of path fragments separated by `/` so there's a ton of valid match combinations which regex searches exhaustively.
with this change, it only matches a single part with `~` in front, `owner` matches a variable path like `a/b/c/d` and repo only matches the last part. so the only variable-length thing is `owner` (in the case of subgroups in gitlab). This makes it run fast again.
I also added a test case that, with the old regex, takes 14 seconds and the …
=> fix(core): fix git url regex matching taking too long

.github/workflows/acceptance-tests.yml, .github/workflows/test_deploy.yml
Not sure why the dependabot is not catching this.
But it is causing all acceptance tests to fail on the repo.
So it is easier and quicker to manually submit this PR.
=> chore: update renku actions to 1.4.1

.gitignore, renku/ui/service/entrypoint.py, renku/ui/service/views/__init__.py
Fixes high severity XSS vulnerabilities reported by snyk. I think these are hard if not impossible to abuse because the parameter in question is looked up in the renku metadata before it is returned. And if the id is not found then the request would fail.
The strange thing is that running snyk locally like `SNYK_CFG_ORG=renku snyk code test` still shows:
```
✗ [High] Cross-site Scripting (XSS) 
Path: renku/ui/service/views/jobs.py, line 103 
Info: Unsanitized input from an HTTP parameter flows into the return value of job_details, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).
```
But if I move the code from `result_response` directly into `renku/ui/service/views/jobs.py` where the error is reported then the error goes …
=> fix(service): snyk xss warnings

.github/workflows/test_deploy.yml, Dockerfile, poetry.lock, pyproject.toml
changes it so flake8 < 5.0.0 is used for python 3.7 and >=6.0.0 for 3.8+
I though about just not running flake8 tests for 3.7 but this is probably easier until we phase out 3.7
=> chore: fix tests with python 3.7

.readthedocs.yaml
since dev and docs are now groups, not extras, `pip install .[docs]` doesn't work anymore. This fixes that
=> docs: fix readthedocs build not installing docs group

.github/workflows/test_deploy.yml, pyproject.toml, renku/command/dataset.py, renku/core/dataset/dataset.py, renku/core/dataset/dataset_add.py, renku/core/dataset/providers/api.py, renku/core/dataset/providers/azure.py, renku/core/dataset/providers/cloud.py, renku/core/dataset/providers/s3.py, renku/core/plugin/implementations/__init__.py, renku/infrastructure/storage/rclone.py, renku/ui/cli/dataset.py, renku/version.py, tests/cli/fixtures/cli_integration_datasets.py, tests/cli/fixtures/cli_providers.py, tests/cli/test_datasets.py, tests/cli/test_integration_datasets.py, tests/service/jobs/test_datasets.py
Support for azure cloud storage similar to what we have for s3.
You can use `renkupythontest1` storage account and `test-private-1` container for testing:
```
renku dataset create azure --storage azure://renkupythontest1/test-private-1
```
Ask me for credentials if you don't have it.
We mount the dataset in `read-only` mode. If we allow writes, then it's really easy to mess up the remote data in the CLI (e.g. deleting, ...). Let's discuss this if we should ever provide a writable mount.
Fixes #3241
=> feat(dataset): support for azure blob storage

renku/core/session/docker.py
=> fix(cli): check for image in registry before pulling and improve error messages

.github/workflows/test_deploy.yml
Fixes #3255 
This should be merged after https://github.com/SwissDataScienceCenter/renku-python/pull/3292 that fixes tests due to template renaming.
=> chore: replace deprecated set-output in GH actions

renku/command/checks/__init__.py, renku/command/checks/workflow.py, renku/core/migration/m_0010__metadata_fixes.py, renku/domain_model/dataset.py, renku/domain_model/workflow/plan.py, tests/cli/test_workflow.py, tests/core/test_plan.py
Fixes plan modification dates and their migration. The issue is that deleting and creating a plan with the same name overrides the first plan in the plan tails index and it won't be accessible through that index.
Fixes #3302 
Fixes #3306
=> fix(workflow): set modification date when deriving a plan

.readthedocs.yaml
`python.version` is deprecated and we set `build.tools.python` already
=> docs: fix RTD config

renku/command/format/session.py, renku/command/session.py, renku/core/errors.py, renku/core/session/docker.py, renku/core/session/renkulab.py, renku/core/session/session.py, renku/core/session/utils.py, renku/core/util/ssh.py, renku/domain_model/project_context.py, renku/domain_model/session.py, renku/ui/cli/session.py, renku/ui/cli/utils/plugins.py, tests/cli/test_session.py, tests/core/plugins/test_session.py, tests/fixtures/communication.py, tests/fixtures/session.py
closes #3289 
closes #3290 
Adds `renku session setup-ssh` command to configure SSH locally for access to a deployment (need to be logged in).
Adds `renku session start --ssh` command that setups of keys in the project for SSH access and configures the local machine for access to a session. Also perfirms `setup-ssh` if not done already.
Adds `renku session open --ssh` command that opens an SSH connection to a session.
=> feat(cli): add SSH support for `renku session`

.github/workflows/test_deploy.yml
Coveralls should be posting code coverage on the repo, but doesn't I think it's because the actions only run on push, not on PR. So from the POV of coveralls, it's never run on a PR and doesn't comment. This should fix that.
=> chore: fix coveralls comments

renku/command/session.py, renku/core/login.py, renku/core/util/git.py
=> fix(cli): set git credentials helper correctly on git clone

renku/core/dataset/providers/s3.py, tests/cli/fixtures/cli_providers.py, tests/core/test_dataset.py
=> feat(dataset): store s3 credentials per bucket

renku/core/dataset/providers/local.py, renku/ui/cli/dataset.py, tests/core/commands/test_dataset.py
=> feat(cli): support rsync-style syntax using / in dataset add

pyproject.toml
Python 3.11 requires global flags (like `(?x)`) to be at the beginning of a regex, having this after some white-space caused installation to fail on Python 3.11.1+
This fixes all tests on `develop`/`master` not running
=> chore: fix install on python 3.11 due to version regex

.github/workflows/test_deploy.yml, poetry.lock
frozendict 2.3.6 doesn't have a source distribution and isn't installable on macos with Python 3.11, but 2.3.7 does :shrug:
Also changes action so branches names "hotfix/*" run tests when merging to master (though this only works once this is merged, hence this branch is named release/...)
=> fix(cli): fix frozendict dependency for Python 3.11 on MacOS

renku/infrastructure/database.py, renku/infrastructure/gateway/activity_gateway.py
fixes the issue reported in https://renku.discourse.group/t/pipeline-takes-ages-and-or-fails/785/8
The database returned uninitialized objects when loading objects from the deserialization cache and the by usage/by generation indices weren't updated in the migration and sometimes pointed at old (deleted) activities.
=> fix(core): fix error in metadata loading and v10 migration

.github/dependabot.yml
I think `open-pull-requests-limit: 0` used to mean "unlimited" but now it means "don't check"
=> chore: fix dependabot not checking poetry dependencies

renku/core/dataset/dataset_add.py, renku/core/dataset/providers/local.py, renku/ui/cli/config.py, tests/cli/test_datasets.py
Fails when adding files from outside the project with `--link`.
Allow configuring `copy`, `link`, or `move` in Renku's local/global configuration. A default value of `link` will be ignored for files outside the project and we'll prompt users.
Fixes #3333
=> feat(dataset): default dataset add action in configuration

docs/spelling_wordlist.txt, renku/command/migrate.py, renku/command/view_model/template.py, renku/core/login.py, renku/core/migration/migrate.py, renku/core/template/template.py, renku/core/template/usecase.py, renku/core/util/git.py, renku/domain_model/template.py, tests/cli/test_clone.py, tests/cli/test_template.py, tests/core/test_template.py, tests/fixtures/templates.py
A Renku-specific section can be added to a Dockerfile.  Any lines of the Dockerfile that are between begin and end end markers must not be modified by users. This section is used to calculate Dockerfile checksum (empty lines and whitespaces at the end of lines are ignored). If it's missing then we use the whole Dockerfile.
When updating a template, Renku only update this section if it exists in both project and template Dockerfile; otherwise, the whole Dockerfile is overridden.
```
########################################################
########################################################
########################################################
########################################################
```
Fixes #3354
=> feat(core): do not update template if dockerfile is modified

renku/command/graph.py, tests/cli/test_graph.py, tests/core/commands/test_graph.py
We need to export provenance tails so we also get deleted datasets into the graph. As it currently is, deleted datasets never show up in triples and will still show up in search.
=> fix(cli): export removed datasets in graph export --full

poetry.lock, pyproject.toml
* build(deps): (deps): bump networkx from 2.6.3 to 3.1
* build(deps): (deps): bump rq-scheduler from 0.11.0 to 0.13.1
* build(deps): (deps-dev): bump pytest-flake8 from 1.1.0 to 1.1.1
* build(deps): (deps): bump deepdiff from 5.8.1 to 6.3.0
* update lock file
* bump poetry-dynamic-versioning
Merging to update 2.4.1 release with poetry bugfix
=> chore: combined dependency update (#3451)

renku/core/storage.py
=> chore: remove unused code in renku lfs migrate

.github/workflows/test_deploy.yml, CHANGES.rst, renku/command/schema/workflow_file.py, renku/domain_model/workflow/workflow_file.py
doctor fix/proper fix can be added with https://github.com/SwissDataScienceCenter/renku-python/issues/3510 later
=> fix(cli): fix wff plan ids

renku/ui/service/jobs/datasets.py, tests/service/jobs/test_datasets.py
=> fix(service): fixes importing private datasets in deployments with external gitlab

Dockerfile
It seems that git lfs 2.x is not available anymore.
Doing the following in Docker causes the same error I have been seeing when trying to build the core service in a CI pipeline.
```
➜ docker run -ti --rm --entrypoint bash python:3.9-slim
Unable to find image 'python:3.9-slim' locally
3.9-slim: Pulling from library/python
5b5fe70539cd: Already exists 
f4b0e4004dc0: Already exists 
ec1650096fae: Already exists 
2ee3c5a347ae: Already exists 
d854e82593a7: Already exists 
Digest: sha256:0074c6241f2ff175532c72fb0fb37264e8a1ac68f9790f9ee6da7e9fdfb67a0e
Status: Downloaded newer image for python:3.9-slim
root@a2d22e73ee16:/# apt-get update
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 …
```
=> chore: update git-lfs to 3.x in core service

helm-chart/renku-core/templates/deployment.yaml, helm-chart/renku-core/values.yaml, poetry.lock, pyproject.toml, renku/ui/service/cache/config.py, renku/ui/service/controllers/api/mixins.py, renku/ui/service/controllers/templates_create_project.py, renku/ui/service/worker.py
with sticky sessions, users could get routed to services that don't have a cached copy of a project, but redis would still say there is a cache.
This isolates redis on a per-service level and also handles the case where a project is in redis but not on disk.
=> fix(service): isolate redis namespace for core-svc instance and properly check if project is cached

renku/ui/service/controllers/cache_migrations_check.py
We can't do the gitlab api path for users that aren't logged in, since we don't have a gitlab token for those.
=> fix(core): skip fast cache migrations check for anonymous users

renku/domain_model/dataset.py, renku/ui/service/serializers/workflows.py
Introduced a bug as part of #3594.
This removes it.
=> fix(cli): do not freeze/unfreeze plan view model

renku/command/config.py, renku/ui/service/views/apispec.py, tests/service/views/test_config_views.py
=> fix(core): setting non-existing config property to null

renku/core/util/contexts.py, renku/domain_model/git.py, renku/ui/service/cache/models/project.py, renku/ui/service/cache/projects.py, renku/ui/service/cache/serializers/project.py, renku/ui/service/controllers/api/mixins.py, renku/ui/service/controllers/project_lock_status.py, renku/ui/service/controllers/utils/remote_project.py, renku/ui/service/gateways/gitlab_api_provider.py, renku/ui/service/gateways/repository_cache.py, renku/ui/service/serializers/common.py, renku/ui/service/serializers/templates.py, renku/ui/service/utils/__init__.py, tests/service/cache/test_cache.py
Normalizes git url in service by removing `.git` postfix.
Fixes #3575
=> fix(service): normalize git url to avoid duplicate cache entries

renku/command/session.py, renku/core/session/renkulab.py, renku/core/session/session.py, renku/core/util/ssh.py, renku/ui/cli/session.py
closes #3585 
closes #3584 
I am not sure that getting into people's ssh configurations to such extent (as we currently do) is maintainable and feasible without a lot of edge cases or bugs. So I decided to simply give a warning when the `renku session ssh-setup` command is used. When I saw this command (including other users from discord) I expected that it would inject ssh keys into the current project. But it does not do this. It only generates/updates stuff in `~/.ssh/renku`. 
I think a more sustainable solution is to step back from doing all this ssh configuration manipulation for users. Because the biggest problem is that it is hard to make things work both with and without using the renku CLI. But we can discuss this further in a separate issue.
=> fix(cli): ssh setup and key usage

.github/actions/install-linux/action.yml, .github/actions/install-macos/action.yml, tests/cli/test_template.py
The test checks for the template name. But we changed the template name so the test fails even though everything works.
=> chore(tests): fix template name check

.github/workflows/test_deploy.yml
removes redis action from macos test since it only works on linux. This test doesn't use redis anyways so everything passed when I tested
=> test: remove redis action from macos

renku/ui/service/controllers/datasets_add_file.py, renku/ui/service/controllers/datasets_import.py
adds timeouts to rq jobs to cleanup metrics dashboard.
ttl=how long a job stays enqueued before failing
failure_ttl=how long a failed job is kept around
=> fix(service): set job timeouts correctly

renku/ui/service/gateways/repository_cache.py
the walrus library does not store None, but turns it into empty string, which would always fail the check.
=> fix(service): fix cache not getting refreshed

renku/core/errors.py
A very minimal cosmetic fix in one error message :)
=> fix: adds missing spaces in OutputsNotFound error message

.gitignore, renku/core/dataset/providers/zenodo.py, renku/ui/service/controllers/datasets_import.py, renku/ui/service/jobs/datasets.py, tests/service/jobs/test_datasets.py
Renaming `name` to `slug` was not done for a service function which caused an exception when importing datasets from UI.
=> fix(service): dataset import error

renku/core/session/session.py
=> fix(cli): use lower case image names for sessions in upper-case projects

renku/ui/service/controllers/templates_create_project.py, tests/service/views/test_templates_views.py
=> fix(service): allow setting keywords on project creation

renku/core/errors.py, renku/core/init.py, renku/domain_model/template.py, renku/ui/cli/init.py
This PR adds a flag to allow ignoring template rendering errors.
Fixes #3696
=> feat(cli): allow ignoring template rendering errors

renku/core/workflow/model/concrete_execution_graph.py, renku/domain_model/workflow/plan.py
=> fix(cli): don't fail on workflows without inputs/outputs and print approriate warnings

renku/command/checks/workflow.py, renku/core/config.py
this PR also introduces a `RENKU_LOCK_PATH` env var that a user can set to put the renku lockfile somewhere else, intended to solve issues users see when their home dir is mounted on NFS.
=> fix: make doctor fix for workflow ids also update oid and derived_from
